### ISSUE TITLE
課題1: 自己紹介

### ISSUE THREAD

**Issue by yofukami** [icat-lab/ay2021spring_icatlab#2]
# 概要
2021年4月21日、第1回基礎ゼミの課題投稿スペースです。
この週は自己紹介を投稿していただきます。
以下の教員が投稿した内容を見本/テンプレートとして、各自で自己紹介を投稿してください。

**Comment by yofukami** [comment]
# 深見嘉明 (教員)
学習院大学経済学部特別客員教授、このゼミの担当者です。
京都出身で、大学から東京在住です。
学習院大学経済学部では、IoT時代のビジネスデザイン、IT企業最前線、テクノロジーマネジメント、プラットフォーム戦略といった科目を担当しています。
詳しいプロフィールは[こちら](https://github.com/icat-lab/CurriculumVitae)を参照してください。
よろしくお願いします。

**Comment by Gucchiy** [comment]
# 山口祥弘 (マイクロソフト)
マイクロソフトにて、ウィンドウズ アプリケーション コンサルタント の アジア・パシフィック リージョンを担当しています。日本では私一人ですので、日本のお客様からの ウィンドウズ アプリケーション コンサルタントは一手に引き受けています。今回、深見先生のお誘いで、（今やマイクロソフトの仲間である）GitHub の使い方などについて、サポートさせて頂きます。[ここ](https://www.gucchiy.com/)とか、[ここ](https://github.com/icat-lab/g4n/blob/main/member_list.md) にも詳しい情報があるかも知れません。
よろしくお願いします。

**Comment by Johnsonliusw** [comment]
# 劉松蔚
初めはして、リュウショウイと申します。
中国の浙江省の出身で、2019年初の時、日本に留学しました。
みんなと友達になりたいですから、僕になんでも聞いてもオーケーです！
興味は特にないけど、ドラマを見ることと美味しい料理屋を探すとこが好きです。
これから、よろしくお願いいたします。

**Comment by aisaaaaa** [comment]
# 橋本愛沙
東京生まれ、東京育ちの江戸っ子です。浅草やスカイツリーの近くに住んでいます！お菓子のTOPPOが好きです。
高校まで６年間陸上競技をやっていましたが、大学では新たにカレッジスポーツを始めるつもりです。
コンピュータには疎いですが授業についていけるよう、同じクラスの仲間と協力しながら頑張りたいと思います。
宜しくお願いします。

**Comment by AyariNomura** [comment]
# 野村彩莉
千葉県出身で実家住みです。部活はテニスをやっていて大学でも続けるか迷ってます。
好きな食べ物は白米と唐揚げです。気軽に話してくれると嬉しいです！
よろしくお願いします！

**Comment by wakabamomii** [comment]
# 籾井若葉
神奈川県の川崎市に住んでます。中高テニスやっていて、大学ではテニスサークルに入ろうと思っています。
吉沢亮が好きです！好きな食べ物はお寿司です。特にサーモンが好きです！
パソコンすごい苦手なので、困った時は助けてくれると嬉しいです。
宜しくお願い致します。

**Comment by 21022163** [comment]
# 権田晴香

大阪生まれ、神奈川県育ちです。
最近は映画を見ることにはまっています。好きな食べ物は、イタリア料理と甘いものならなんでもです！
大学では、実委とダンスを兼サーしようか迷っています。
パソコンは超初心者なのですが、精一杯頑張ります。
よろしくお願いします。

**Comment by amanemasuda** [comment]
# 増田普音
埼玉県さいたま市出身です。　
小中高で野球をやっていました。高校でけがをしてしまい、大学ではマネージャーとして硬式野球部に入部しました。
いつでも話しかけてください！これからよろしくお願いします！

**Comment by Rinne614** [comment]
# 小林凜音
埼玉県に住んでいます。
趣味は音楽鑑賞で、最近は部屋の模様替えにはまっています。
パソコン初心者なので、たくさん学んでいきたいです。
よろしくお願い致します！

**Comment by Gucchiy** [comment]
テスト

**Comment by MioAkiyama0223** [comment]
# 秋山美桜
神奈川県出身です。中学では、体操部に入っていて高校では帰宅部でした。大
学では、マネージャーをやりたいなと思っています！最近は、韓国ドラマを見ることとジャニーズにはまってます。ぜひ仲良くしてください。よろしくお願いします！

**Comment by SayakaFujikawa** [comment]
# 藤川紗亜花
（ふじかわさやか）です。
神奈川県住みです。
音楽が好きでアコギ弾きます。基本的に何でも聞きますがback numberが特に好きです。
この前の身体計測で去年より１cm身長が伸びたので、成長期が来たような気がして喜んでいます。
よろしくお願いします！

**Comment by shioriko-tokunaga** [comment]
# 德永栞子
初めまして。埼玉県さいたま市に住んでいます。
高校の時は弓道をやっていて、大学では少林寺拳法部に入部しました。
趣味はジャニーズとか音楽を聴くことです。
パソコンは初心者ですが頑張って学んでいきたいです！よろしくお願いします。

**Comment by HirotoGoto** [comment]
# 後藤洸登
横浜市出身です。
高校ではボート部に所属していました。大学ではバレーのサークルに入ろうか、と考えています。
趣味は音楽を聴くことです。RADが好きです。
よろしくお願いいたします！

**Comment by yadoiwa** [comment]
# 宿岩芽梨香
（やどいわめりか）
埼玉県出身です。
kpopが好きです！バドミントンサークルに入ろうと思っています。
パソコンは苦手ですが、よろしくお願いします！

**Comment by seshitamayu** [comment]
# 瀬下茉由
(せしたまゆ)です。
神奈川県横浜市出身です。
出かけることと食べることが好きで、餃子とアイスが好きです！
部活はソフトテニスとダンスをしていました。
大学では実委と、テニスかダンスかで迷っています。
パソコン初心者ですが、色々吸収して頑張ります。
よろしくお願いします！

**Comment by yui423i** [comment]
# 石橋由衣
東京住みです。中高共にソフトテニス部に所属していました。
最近は餃子にハマってます。漫画を読む事が好きです。
パソコンは苦手ですが、徐々に慣れていきたいと思います。よろしくお願いします！

**Comment by mi513** [comment]
# 大島美怜
埼玉県に住んでいます。
趣味は音楽を聴くことです。　特にジャニーズが好きです！
仲良くしていただけると嬉しいです！　よろしくお願いします。

**Comment by KarenTakamatsu** [comment]
# 髙松かれん
東京生まれ、東京育ちです。
8年間フラダンスをしていました。
好きなことはドライブ、海外旅行、音楽を聴くことです。
特にK-POPが好きなので同じ趣味の方がいらっしゃれば嬉しいです。
よろしくお願い致します！

**Comment by shofukurono** [comment]
# 袋野奨
神奈川県茅ケ崎市出身の湘南ボーイです！！今も茅ケ崎に在住で大学まで通ってます！
小学校から高校までずっと野球やってました！！！
大学では野球を続けるか迷っていますが、何かしらのスポーツはやりたいと思ってます！
趣味はドライブやカフェ巡りです！
これからよろしくおねがいします！
