### ISSUE TITLE
課題2: 輪読1-1 稲葉 『社会学入門』 第1講 理論はなぜ必要か の要約

### ISSUE THREAD

**Issue by yofukami** [icat-lab/ay2021spring_icatlab#3]
# 概要
[課題提出見本テンプレート](https://github.com/icat-lab/ay2021spring_icatlab/issues/1) にのっとって、輪読課題である　"稲葉 『社会学入門』 第1講 理論はなぜ必要か"の要約を各自投稿してください。

# 締切
- 5月3日(月)23:59
- ただし、その週の担当者の方が余裕を持ってまとめ作業ができるように、できるだけ早めに投稿してください。
-  投稿したら、その週の担当者にチームのSlackチャンネルで教えてあげてください。

# 輪読の流れ
[こちら](https://github.com/icat-lab/icat_lab/blob/master/basic_seminar_undergrad/literature_review.md)を参照ください。

**Comment by shioriko-tokunaga** [comment]
# 德永栞子　グループ2
# 要約

1. **社会学の理論～共有しているものは何か～**

- 学問は基本「分業」→社会科学もたくさん枝分かれしている　ex）社会学、経済学、政治学
- 社会学には根底の「理論」が薄い
- そもそも理論は何に役立つのか

2. **統計調査をもとに関係を読み取る**（本文では失業率と犯罪、自殺率を取り上げている）

- 数字を眺めるだけでは何も見えない→連動する複数の数字を見つけることが◎
- 数字の規則的な関係を見つだすことが、社会科学の第一歩

 

3. **社会科学のある理由と因果メカニズムの理解**

- あらゆる社会の問題の解決に役立つ→「世のため人のため」のものになる
- その環境や状況によって、自分が一般的に考えていた相関関係が変化することもある（新たな原因が見えたりもする）
- 何が原因で何が結果なのか、背後にあるメカニズムから理解することが重要
- 「理論」は少なからずその道具として必要

4.  **社会科学における研究の方法は？**

- ①統計的な大量観察
大量のデータから条件の違うものを取り出す→‘’比較‘’
手間はかかるが、既存のデータセット（ex.国勢調査）の利用も可能

　　②歴史研究
　　過去の出来事のデータを集める→‘’比較‘’→法則を見つける、因果を探す

①と②に共通すること　**コスト、倫理の面で優れている**

- 個別の具体例を徹底的に解明するスタイルもある【ケーススタディ】
→これらを組み合わせて、‘’比較‘’研究の材料となる
→研究する上での道具として「理論」が必要

# 感想
第１講を読んで、社会学が何かという問いよりも先に、根本的な理論とは何かについて語っていて、確固たる「理論」の存在は未だに少しあいまいな部分があったが、研究していく上での一つの目印のようなものなのだと理解できた。
よく、大学のパンフレットなどで社会学部の概要をみると、必ずと言っていいほど学問が枝分かれした図が載っている。あらゆる分野を学べる学問として、今回登場した「道具としての理論」とは社会学において具体的に何なのか、この本を読み進めて自分も考えていきたい。

**Comment by MioAkiyama0223** [comment]
# 秋山美桜　グループ２
# 要約
**社会学の今**
社会学以外の学問は、共通の基礎として踏まえている「 基礎理論」「一般理論」が存在している。しかし、社会学は理論を作る各々の人に違いがあるために理論の存在が希薄しているのが現状である。

**そもそも理論とは何か、何の役に立つのか。**
社会学の科学的な分析の第一歩として、単に1つの数字だけを見て傾向をとらえるのではなく、連動した複数の数字を見てそれらの数字の間に一定の規則的な関係が成り立つことを見つけ出すのが重要であり、これらにどのような因果関係があるのかを考えなくてはならない。このメカニズムを説明するのが理論であり、社会学は社会問題に役立つ知識を提供する学問である。

**なぜ理論は必要?**
社会問題の因果メカニズム理解するためには、ただ事実を観察するだけでなく理論が必要である。

**理論を検証する方法**
ではその理論を検証する際、社会科学には物理・科学・生物学・心理学などの他の学問とは異なり問題が発生する。まず、社会学は実験の対象を探すことが困難である。また、対象を探し終わったうえでそれをただ観察するだけではなく生活に介入してしまうために問題が発生することもあるため、調査が困難になってしまうのである。そのため、実験の代わりとして、統計的な大量観察と歴史研究を行う。このどちらもコスト・倫理面においては非常に有効なものである。こうした大量観察データの統計的な解析を「量的調査」と呼ぶのに対し、「質的調査」または「ケーススタディ」と呼ばれる研究もある。

**理論の必要性、そして社会学の成り立ち**
ケーススタディの場合、因果関係がはっきり見えてしまい理論が必要ないかのように思えるが、そういった研究において、思考と分析を助けるための道具として理論はやはり大切なのである。社会学は、ほかの学問と違い、研究対象も共通しておらず、学問アイデンティティが成り立っていないのが現状であるが、共有されているものがみえる時代があったからこそ社会学が成り立ったのだ。
# 感想
第１講を読み、「社会学とは何か」について自然科学や政治学などの他の人文社会系学問と対比させる形で成り立ちや理論の検証を述べていてわかりやすく、そしてとても面白く感じました。講義の最後までには、社会学のある程度の学問に対するイメージをつかめるよう学習していきたいです。また、学問アイデンティティが成り立っていない現状の社会学が、共有されているものが見える時代があったからこそ社会学が成り立ったと書かれていましたが、それはいったい何なのか次回の講義までに考えておきたいです。

**Comment by mi513** [comment]
# 大島美怜　グループ２
# 要約
#### 社会学の理論と他の学問の理論
社会学以外の他の学問には共通の「基礎理論」「一般理論」というものがありその理論から他の理論「特殊理論」「応用理論」を派生していくのに対して、社会学は理論の共通性が薄くたくさんの理論がある。多くの学問は時間が経過すると一つの理論を作り出すが、社会学は理論をそれぞれが作っているがゆえに理論間にかなりの差がありまとまる様子もない。

#### 理論の必要性
共通認識があまりない社会学に理論は必要なのか？
→社会問題を解決する際に因果関係が重要になり事実を観察するだけではなくて理論が必要となってくる。（本文では失業と自殺の例で話されている）
個別研究に焦点を当てたとき因果関係がはっきりとしてしまい理論は必要ないとされるが、個人研究だけで社会が成り立っているわけではないので理論の重要度が落ちることはあっても完全に不要になるわけではない。また個人研究においてもすべてが完璧であることはないため個人研究にも思考と分析を助けるものとして理論は必要である。

# 感想
今まで社会学について考えたことはなかったので読んでいて面白かったです。社会学は他の学問と同じだと思っていたけどそうではないことを知りどのように違っているのか、そして共有されているものが少ないのになぜ社会学が成り立っているのかをこれから知っていきたいです。

**Comment by Johnsonliusw** [comment]
# 劉松蔚 グループ1
1️⃣社会科学の中、社会学は唯一の明確な「論理」が持っていない学問
　社会学者たちは自分だけ関心する問題を研究し、社会を理解するための理論を学ぶ。この場合では、それぞれの共通性がかなり希薄だ。結果は社会学の理論の源流たる「基礎理論」と「一般理論」のようなものが見当たらない。

2️⃣社会学の「論理」とは何か？存在の理由
•実際データに基づく仮定推論を通じて物事の発展規律と問題の因果関係を解明できるメカニズムは社会学の「論理」である。
•このメカニズムを用いて世のため人のために役に立つ、「因」を探し、「果」の社会問題を解決する。

3️⃣社会調査の方法
•統計的大量観察（本文では失業率と犯罪、自殺率の関係を取り上げた）
　1、定期定量な調査対象（ランダムサンプリング）を選び出して調べ、相関のデータを獲得する。
　2、獲得したデータをお互いに比較して社会問題のつながりを捉える。（社会の科学的分析の第一歩）
•歴史研究
　1、過去にすでに起こしたことを素材として、現在進行の実態調査と比べて推測する。
•「ケッススタディ」＝「質的調査」：個別の例を具体的に分析すること。（個人的能力とり「論理」を持つ方が重要）

# 感想
　社会科学にはどちらの科学でも物事のつながりを研究している。社会学では、共通理論が明確に定着していないとしても、全ての学科と関わっている。限定している範囲がなく、かえって持っている可能性と包容性が全部の学科の中で一番高い。社会学は学科と言うより、むしろ研究と思考をうまくいく道具だと思う。

**Comment by amanemasuda** [comment]
# 増田普音　グループ１

# 要約

### 社会学の理論の現状　
- たいてい学問研究は各々が分業で行い、共通の基礎理論が存在するが、社会学の場合にはそのような理論が多く、それぞれの理論間で共通性が薄い。
### 理論とは？
- 社会の科学的な分析の第一歩は複数の数字間から一定の規則的な数字を見つけ出すことであるが、この際に発見した数字の連動にどのような因果関係やメカニズムがあるのかを説明するのが「理論」である。
### 社会学と理論の存在理由
- 社会学が存在する理由は社会問題の解決に役立つ知識を提供することで「世の中の人の役に立つ」と思われているからである。
- 社会問題を解決するにはまず因果メカニズムを理解することが必要で、そのためにはただ単に事実を観察するだけではなく理論が必要となる。
### 社会学における実験
- 物理や化学の実験とは違い社会学では人為的で大規模な実験が必要である。ただ社会学では対照実験を行うことが非常に困難である。
- しかし社会科学の実験の代わりとして、統計上のデータを用いて理論の適合性を検証する「統計的な大量観察」と過去の出来事の記録を集めて比較する「歴史研究」が置き換えられる。また「ケーススタディ」のような、個別のケースを徹底的に解析するというスタイルの解析も行われる。
### 社会学の特殊な状況
- 社会学の中で理論に関しては全体としての共通見解がほとんどないという状況に陥っていて学問的アイデンティティが非常に揺らいでいる。ただ共有されているものがないわけではない。

# 感想
これまで社会学がどういうものかよくわからなかったが、他の学問と比較してみると違いが多く、より知識を深めていきたいと感じた。また社会学における理論の重要性を知ることができた。文中最後に問いがあることで次回に向けての意欲が増した。問いに対する答えを考えていきたい。

**Comment by yui423i** [comment]
# 石橋由衣　グループ2

# 要約
**社会学の理論**
社会科学の中でも社会学の「誰でもが共通の土台としてふまえる基礎理論」である「基礎理論」「一般理論」は多くの社会学者が各々に作っているので共通性が希薄であり、かなりの違いがある。

**理論の必要性**
社会学が社会問題の解決に役立つためには、社会問題を引き起こしている因果関係のメカニズムについての理解である。因果メカニズムがわからなければ、解決のための手を打てないし、因果メカニズムを理解するためには理論が必要なのである。そしてその理論の正誤を確かめる際、「統計的な大量観察」、「歴史研究」が実験の代わりとして行われる。
一方で個別のケースに焦点を当てる研究においては理論の重要度が落ちるように思われる。しかし、1つの個別研究だけで社会の実証研究が成り立つわけではなく、他の個別研究と組み合わせて比較研究の素材となることもありうる。その比較研究の素材として理論が必要となるのである。また、社会学者の思考と分析を助けるものとして理論は必要である

# 感想
社会学について何も知らない状態だったが、この文章を読んで興味を持つことができた。基礎理論が定まっていない状態で物事を考えることは自分には真似できないことだと思った。共有されいるものが少ないものの、共有された部分が見えた時代があったということについて関心を持った。

**Comment by aisaaaaa** [comment]
# 橋本愛沙　グループ１
# 要約
**社会学の理論の現状、アイデンティティ**
自然科学群や社会科学の他の学問が持つような「基礎理論」や「一般理論」といった各々の学問で根底とされるものがはっきりと存在せず、共通性の薄い理論で溢れかえっている。また、問題関心の対象も共通しておらず、学問的アイデンティティが非常に揺らいでいる

**【具体例】失業率と犯罪、自殺率**
→複数の数字(数値)を見て初めて社会科学的な面白さは生じ、そこで一定の規則性が成り立っていることを見つけ出す作業が社会の科学的な分析の第一歩である

**社会学、「理論」の存在理由**
社会学の重要な存在理由は現実の社会問題の解決に役立つ知識を提供するとされているから。社会問題等における因果関係は統計数字の連動を見て推測するしかない。その背後にどのような因果メカニズムが働いているかを考える際に用いられるものが「理論」である

**社会学の理論検証方法**
社会学の「実験」は他の学問とは異なり、大規模かつ条件の均一性に困難が付きまとうため
①統計的な大量観察（条件の異なる統計上のデータを用いて理論の適合性を検証）
②歴史研究（過去に起きた出来事を集めて比較する）　　が用いられる。
どちらも既存のデータや資料で検証可能でコストを抑えることができ、倫理問題が起きにくいという長所がある。
また「ケーススタディ」と呼ばれる、ある個別の事例に照準を絞り込み徹底的に解明する方法も存在する。この場合、他の研究と組み合わせ比較研究の素材になるうえで比較の道具となる「理論」が必要となる

# 感想
社会学は「社会学」という名前が付けられているものの、その実態は各々の研究で生まれた理論が飽和状態にもかかわらず「基礎理論」としてまとまっていないうえ、20c末あたりから理論に関して社会学全体としての共通認識がほぼ無くなっている。直前の内容を文字に起こしてみて改めて驚いたが、このような学問が今まで存続してきたのはかえってそのストライクゾーンの広さ、順応力の高さから来るのかもしれないと感じた。第１講で重要視された「理論」を気にしながら次回以降も読み進めたい。

**Comment by yadoiwa** [comment]
# 宿岩芽梨香　グループ2
# 要約
学問には、基本的に「一般理論」や「基礎理論」がある。しかし、社会学はそれぞれの理論の間の共通性が希薄である。
#### 社会学にとっての「理論」
数字の間に一定の規則的な関係を発見していく作業が社会の科学的な第一歩である。そしてその数字の連動という現象の背後のある現象を生み出す因果関係のメカニズムを説明するものが「理論」である。
因果関係は断言ができず推測するしかないため、因果関係のメカニズムを理解するために丹念的に事実を観察するのではなく理論が必要となる。
#### 社会学の実証的な研究
社会学以外の学問では実証的な研究というと実験を行うことが多いが、社会学で取り扱う現象は複数の理論的仮説の適合性の良さを比較する実験をすることが困難な規模の広さである。そこで社会学では実験の代わりに統計上のデータを用いて理論の適合性を検証する、統計的な大量観察と過去にすでに起きてしまった出来事の記録を比較する歴史研究を行う。
#### ケーススタディと理論　
統計的な大量観察と歴史研究のほかに、ケーススタディと呼ばれる、個別ケースに照準を絞り込み、それを徹底的に解明する研究も行われる。この研究方法の場合、個人的な洞察力や名人芸があればそれぞれの共通性である理論は不要だと考えてしまう。しかし、個別研究はほかの個別研究と組み合わせて比較研究の素材となることで新たな生命を獲得できるため、思考と分析を助ける道具として「理論」が必要である。
#### 社会学の共通性
社会学に理論が必要だ。しかし社会学全体としての共通見解はほとんどないため、学問的アイデンティティが揺らいでいる。社会学という学問が成立した原因である社会学に共有されているものは何だろうか。
# 感想
社会学の実証の1つである数字の間にある一定の規則的な関係の発見についてや社会学で取り扱う分野の規模の広さなどをわかりやすい例を用いて述べられていたため理解しやすかった。社会学は社会問題について幅広く調査していることやその調査方法について知ることが出来たので次はさらに深く掘り下げたい。また、社会学という学問が成立した原因となった共通性は何なのか次回の講義で明らかにされるのが楽しみだ。

**Comment by wakabamomii** [comment]
# 籾井若葉　グループ１

# 要約
**社会学の理論について**
社会学以外の他の学問は共通して『一般理論』や『基礎理論』が存在しているが、社会学にはこのように軸となる理論は無い。
社会学者は個人で理論を作っている場合が多く、それら共通性は希薄である。

**理論の必要性・存在理由**
社会の科学的な分析の第一歩→連動している複数の数字を組み合わせて、規則性や共通点を見つけること
その具体例として、失業率・犯罪・自殺率に関係する数字が同じような動きをしていることが挙げられる。
だが数字だけを見て判断してしまうのは情報が不十分なため、因果関係を見つける必要がある。
→そのメカニズムを説明するために必要となってくるのが『理論』である。
理論は実際の社会問題に対し、『世のため人のため』に役立つもの。

**因果関係を見つける方法**
一緒に変動している数字を見てもどちらが原因、結果になっているのかは読み取れない。
因果メカニズムを理解するために用いられるのが主に二つの方法。
❶統計的な大量観察→統計上のデータを用いて理論の適合性を検証する方法
　　　　　　　　　　手間はかかるがあらゆる視点から比較することができる
❷歴史研究→過去に起きた出来事の記録を集めて比較する方法、倫理問題が起きにくいのがメリット
どちらもコストを抑えることができるという共通点がある。
また『ケーススタディ』という方法もある。これはたくさんのケースを比較するのではなく、個別ケースに照準を絞り込み徹底的に解明するというスタイルである。研究する上での道具として『理論』が必要。

# 感想
社会学は他の学問と比べると違う点が多くあり、とても興味深い内容だった。失業率や犯罪、自殺率の関係性を例を出していることによって、社会学における理論の重要性についてわかりやすく学ぶことができた。共有されているものが少ないにも関わらず、なぜ社会学というものが成り立ったのか、次回はより理解を深めていきたいと思う。

**Comment by AyariNomura** [comment]
# 野村彩莉　グループ１
# 要約
社会学には他学問と違い理論の共通性が希薄で「基礎理論」「一般理論」のようなものが存在しない。しかし、複数の数字を見た時、規則性を見つけて因果関係を説明する際に「理論」が必要となる。理論の正誤を確かめるには、社会科学において難しい「実験」の代わりとして、統計的な大量観察、歴史研究が重要視される。統計的な大量観察は大量のデータの中から条件の異なるケースを選び比較する方法であるのに対し、歴史研究は過去に起きた出来事の記録を集めて比較する方法である。どちらも倫理問題が起きにくく、コストを抑えられるという利点がある。また、色々なケースを比較するのではなく個別ケースを徹底的に解明する方法もある。この場合は理論が不要に思われるが、他の個別研究との組み合わせによって初めて生かされるため、また思考と分析を助ける道具として理論は必要である。
# 感想
社会学は他学問とは異なっていること、また理論の重要性を知ることが出来た。社会学が学問として成り立つ理由を考えていきたい。

**Comment by KarenTakamatsu** [comment]
# 髙松かれん　グループ１
# 要約

 **社会学の理論の現状**

・学問には基本、「一般理論」と「基礎理論」がはっきりしているが、社会学にはそれらがありすぎて逆に見当たらない。
・学者各々が全く違うテーマで研究しており、共通理論がない。
・社会学のみ対象が共通していないため、学問的アイデンティティが揺らいでいる。

**理論の意味と社会科学の存在理由**

・統計数字を見ながら数字の間に一定の規則的な関係が成立していることを見出すのが「社会学的分析」。
　その分析から、どのような因果関係（メカニズム）があるかを説明するものが「理論」。
・社会科学は実際社会問題の解決に役立つ知識を提供するために存在している。

**社会科学の難しさと対処法**

・因果関係を突き止める際にある変数同士が統計的に関係しても実際は因果関係や影響関係がない場合がある。
　つまり、真の「原因」が隠れている可能性がある。
・そもそも、因果関係は推理するしか見出す方法はない。
・社会問題の因果メカニズムが分からないと解決ができない。　　

［方法１］ 統計的な大量観察　
　　　　　　→統計データを用いて理論の適合性を検証する。
　　　　　　　大量の中から様々なケースを選び出して互いに比較する。
［方法２］ 歴史研究
　　　　　　→過去に起きた出来事の記録を集めて比較する。
　　　　　　　倫理的問題やコストが少ないのがメリット。

**理論とケーススタディ**
・上記から理論は必要。
・具体的に個別ケースに絞り込んで研究する「ケーススタディ」にも理論が必要。

# 感想
学問の中で、社会学のみ共通理論がなく、様々な面で異なっていることが分かりました。しかし、社会学にはこれらの性質があるからこそ、自由で柔軟性があり、社会で幅広く活躍されているのだと思いました。また、「理論」の概念をしっかりと理解していなかったので、改めて知識として蓄えることができました。個人的に難しい内容でしたが、メモをとりながらまとめ、要約として書き出すこと楽しいと感じました。

**Comment by shofukurono** [comment]
# 袋野奨 グループ2
# 要約

* 社会学の現状
社会学以外の学問は理論の基礎に「一般基礎」「基礎理念」があるが社会学はなく、それぞれの理論の共通性がかなり希薄。

* 社会科学の存在理由と理論の意味
複数の数字の間に一定の規則的な関係が成り立つことを見つける作業が社会科学的な分析の第一歩。
理論とは物事の因果関係を生み出すメカニズムを説明するもの。

* 社会科学における実験
①統計的大量観察
大量のデータ観察の中から様々な条件のケースを選び出してきて互いに比較する。
コスト面、倫理面から非常に有効。
②歴史研究
過去に起きた出来事の記録を集めて比較する。
倫理問題が起きにくく、やろうと思えば一人でできるところがメリット。

* ケーススタディに理論が不要か
理論が不要とまで言い切れない。また、思考と分析を助ける道具として理論は必要。

# 感想
今まで身近に感じていなかった研究するということの難しさや物事の因果関係を突き止めるまでの地道さを感じることができた。

**Comment by seshitamayu** [comment]
# 瀬下茉由　グループ２

# 要約

### 社会学の現状
自然科学の場合、共通の基礎としてふまえている「基礎理論」「一般理論」というものはある程度存在しているのに対して、社会科学の中でも特に社会学では、各々の興味関心に応じて理論を学び作っているが、共通の理論ははっきりと見当たらず、理論間の共通性がかなり希薄である。

### 理論とは
社会学において、ある物事を分析する際には、単に一つの数字だけを見るのではなく、連動している複数の数字の動きの組み合わせを見つけ出していくことが、統計数学を見ながら社会について考える基本である。ここで、数字の連動という現象の背後にある現象を生み出す仕組み、メカニズムを説明するのが「理論」である。

### 因果関係
複数の数字の連動を見つけた単なる相関関係ではなく、因果関係自体をわれわれが考えて推測して相関関係の背後にあるメカニズムがどのように働いているのかを考えることが必要である。

### 社会科学においての実験
社会科学においては、自然科学のように研究対象を現実の世界から切り離された人口環境の中に閉じ込めて行うことができない。そのため、社会科学の研究は統計的な大量観察、歴史観察が重要になってくる。
大量観察においては研究者がいろいろな条件を意図的に作り出す必要がなく、国勢調査をはじめとした公的機関が政策実施の基礎データとするために集めた既存のデータセットを利用するため、相手の生活に介入・干渉することなく大量のデータの中から様々に条件の異なるケースを選び出して互いに比較することができる。
また歴史観察においては、過去の出来事の記録を集めて比較する方法をとるため、現在進行中の実態調査に比べて倫理問題が起きにくく、既存の資料を読み込むので独力で行うことができる。
社会学においてはこの二つの研究方法のほかに、「ケーススタディ」と言われるたくさんのケースを比較するのではなく個別ケースに照準を絞り込み、それを徹底的に解明するというスタイルの研究もある。

### 感想
自然科学などの学問には共通の理論があって社会科学の中でもとりわけ社会学には共有されているものがないことすら知らなかったため、社会学とほかの学問との比較、理論の定義、社会学の研究方法、などの開設を読んで社会学について興味を持った。また、読み進めていくうちに社会学には共有されているものがないのに成り立っている理由をその詳しい解説とともに知りたいと感じた。

**Comment by Rinne614** [comment]
# 小林凜音　グループ２
## 要約

**社会学の理論の現状**

社会学以外の他部門においては理論の基礎に「一般理論」「基礎理論」があり、そこから個別の理論へと枝分かれするが、社会学の場合はそれぞれの理論の共通性が希薄である。社会学では「一般理論」を作っている人がたくさんいるが、他部門のように壊し、直しされていく過程がなく、収斂する気配がない。

**社会科学における実験**

理系の実験のように「実験室」という人工環境に閉じこめることができないため、条件をそろえてピンポイントの比較を行うことが難しい。実験に代わってできることは、統計的な大量観察と歴史研究である。統計的な大量観察をすることで、相手の生活に介入する頻度とコストを減らすことができる。歴史研究では過去のことを相手とするので圧倒的に倫理問題に触れる危険性が少なくなる。

**理論の必要性**

社会問題の解決に社会学が役に立つためにも、社会問題を引き起こす因果関係のメカニズムを知る必要がある。そして、数字の連動というような現象の背後にある現象を生み出すメカニズムを説明するのが理論である。
なお、個別研究は他の個別研究と組み合わせて比較研究の対象となって初めて価値が上がるため、比較の道具として理論が必要になる。

## 感想

第一章では特に理論の必要性と社会学における実験の方法について深く知ることができた。学問全体としての共通理解がほとんどなく、研究の対象が絞られていない社会学がどのようなニーズを満たすために誕生したのか、どのようなアイデンティを持つ学問なのかを疑問に思った。

**Comment by SayakaFujikawa** [comment]
# 藤川紗亜花　グループ1
# 要約

**社会学の理論の現状と存在理由**

一般的な学問の研究ではそれぞれに共通するシンプルな共通認識として「基礎理論」ないし「一般理論」があるが、社会学はそれらを作っている人がたくさんいてなお且つどれも異なるため、社会学には「各論」の基底としての「総論」が形作られていない。
しかし共有する常識としての理論は実証のためにとても大切なものである。
それでも社会科学の研究のために世の中でお給料を払われていたり研究費を与えられている人がいるのは世のため人のためになると思われているからである

**社会科学における実験の難しさ**

単に複数のグラフから一緒に変動している複数の数字を見つけただけでは、これらが因果関係にあるのか、模擬相関関係にあるのかは判断できない。しかし因果関係を統計で見つけることはできず、実際は理論を用いて推測することしかできない。
理科的な実験と異なり、規模が大きく、コストがかかる上、実験者を全く同じようにコントロールするのは極めて難しく、倫理的な面においても社会科学における実験をすることは困難である。

第一の方法:統計的な大量観察

社会科学においては実験が困難であるため、大量のデータの中からさまざまな条件の異なりケースを選び比較できる、コスト面でも倫理面でも有効な大量観察の統計的分析を利用することが多くなる。

第二の方法:歴史研究

統計的研究と少し似たような面があるが、統計的研究よりも倫理面、コスト面、パワー面で有効な場合が多い。

**ケーススタディは理論には不要か**

個別の事柄に絞って調査するとき、あるいは内側から調査する時、一見理論は必要でないが、個別ケースが他の個別研究と比較されることによって初めてそれが研究の素材になるのであり、比較の対象として見るためにも、大半の社会学者が平凡な人間であることを踏まえても、常識としての理論は必要である。


# 感想
社会学においての理論があるか否かについて考えたことがなかったが、読んでみるとすごく興味深くて文章も丁寧に説明してあり理解しやすかった。

**Comment by 21022163** [comment]
# 権田晴香　グループ１
# 要約
**1. 社会学の理論とは**
・共通の基礎である、「基礎理論」「一般理論」が見当たらない。共通性が希薄。
・理由として、研究者それぞれの「基礎理論」「一般理論」の間にかなり違いがあり、他の学問と違って皆で一つの大きな理論を作り上げ、収斂することがないことが挙げられる。

**2.理論の意味と社会学の存在理由**
・物事を生み出すメカニズムに、どのような因果関係があるのかを考える仕組みを説明したものが理論。
・社会学の存在理由は、単なる娯楽ではなく、実際に社会問題の解決に役立つ知識を提供するから。

**3.因果関係**
・数字同士が連動しているだけではわからない。
・因果関係は、自分たちで考え、推測するしかない。→観察するだけではダメなので、ここで**理論**が必要となる。

**4.社会科学における実験**
①統計学的な大量観察
・統計上のデータを用いて理論の適合性を検証する
→手間はかかるが、データ収集や、調査対象に介入・干渉することが無い。
②歴史研究
・過去の記録を集め、それらを比較する
→倫理的問題は起きにくく、大人数で調べる必要もないが、まだるっこしいし、不完全なものになりかねない

**5.ケーススタディ**
・個人研究の場合、比較の素材として必要となる。

# 感想
そもそも、学問には共通の基礎である「基礎理論」「一般理論」があることを知らず、学問の仕組みについて知ることもできて面白かった。社会学は他の学問とは違って、きちんとしたまとまりが無く、割とめちゃくちゃなのに、どうして成り立ったことにとても興味が湧いた。
筆者が言葉を噛み砕いて、解説してくれたので、とても読みやすかった。

**Comment by HirotoGoto** [comment]
# 後藤洸登 グループ１


# 要約
**社会学の理論の特徴**
 学問には多様な理論が存在するが、そこでは基礎の部分に「一般理論」や「基礎理論」があり、そこから枝分かれ方式で「特殊理論」「応用理論」へと発展していくのが一般的である。しかし、社会学の場合は「一般理論」「基礎理論」の数が多く、それぞれの主張が違うため、基礎の部分で共通理念がないのが現状である。

**理論と社会科学の存在意義**
 あるいくつかの現象に関する数字が連動している場合、連動しているメカニズムを説明、解明するために使われることが、「理論」の存在意義である。社会科学は社会問題の解決に役立つ知識を提供するために存在している。

**相関関係と社会科学の実験について**
 前項で上げたいくつかの現象が連動している場合、そこには相関関係が存在する場合がほとんどだ。その中にはどちらかの影響でどちらかが変化する「因果関係」や真の原因が別に存在する「疑似相関関係」などがある。そのため、因果関係を正しく理解する必要があり、そのためには実験が必須である。
 しかし社会科学の実験は難易度が高い。それはどうしても規模やコストが高くなるからで圧。例えば似通った町２つを使って対照実験を行う場合、街を探し出すコスト、街を利用するコストなどがかかる。

# 感想
 第１講ではわかりやすく理論の必要性と社会学の特徴について書かれていてとても興味深かった。
