### ISSUE TITLE
課題3: 輪読1-2 稲葉 『社会学入門』 第2講 「モデル」とは何か の要約

### ISSUE THREAD

**Issue by yofukami** [icat-lab/ay2021spring_icatlab#4]
# 概要
[課題提出見本テンプレート](https://github.com/icat-lab/ay2021spring_icatlab/issues/1) にのっとって、輪読課題である　"稲葉 『社会学入門』 第1講 理論はなぜ必要か"の要約を各自投稿してください。

# 締切
- 5月10日(月)23:59
- ただし、その週の担当者の方が余裕を持ってまとめ作業ができるように、できるだけ早めに投稿してください。
-  投稿したら、その週の担当者にチームのSlackチャンネルで教えてあげてください。

# 輪読の流れ
[こちら](https://github.com/icat-lab/icat_lab/blob/master/basic_seminar_undergrad/literature_review.md)を参照ください。

**Comment by shioriko-tokunaga** [comment]
# 德永栞子　チーム2
# 要約

1. 「理論」が希薄している社会学

- 研究を始めるうえでの共通の入り口（理論）がはっきりしない→古典を読む（相場の理解）
- 似通う部分はあるが、基本的には独立した別々の理論であふれている
- 研究対象はバラバラ

2. 「モデル」を使った考え方（経済学を例に取り上げている）

- ‘’方法論的個人主義‘’→社会を個人の集まりとしてとらえて考える、理論構築の発想の仕方
- 分析対象とする個人→「合理的経済人」としてモデル化する
- モデル＝模型　実験に利用する
「理論」＝思考実験　頭の中や紙の上で研究の模型を作ってシミュレーションする
最近ではコンピューターを使ったやり方が発展している

3. 経済学のモデルのとらえ方（戦争ゲームとの対比）

- 「合理的経済人」→自分の利益のために、自らの目標に向かって過程を踏んでいく 
　　　　　　　　　組織であれ、個人であれ、経済的な利益のために合理的（効率的）に動く
- 「戦争ゲーム」→たくさんの前提をもとに、シンプルな結論に向かう（社会学の考え方はこちらに近い）

4.  生物進化と合理性の考え方の類似点
 - 生物の個体を一つのロボットとし、動かすプログラムとしての遺伝子が存在すると考える（モデル化）
 - ある環境の中で、多様なロボットが試行錯誤の末、生まれてくる

5. ロボット・モデルを社会学へ拡張する　
- 経済活動に当てはめる
生物個体→主体　ex．人間、企業、家計
遺伝子→知識と情報　 ある環境の競争の中で、効率的な生産方法や経営のノウハウを持つものが生き残る 
繫殖→模倣、学習、コミュニケーション　

- 主体同士の意思決定と行動を分析する「ゲーム理論」
社会学に影響を及ぼしているのは確かだが、社会学の全体の基礎づけは不可能ではないかと疑問は残る

# 感想
社会学を追求するうえで関わる経済活動の体型に、ロボットをモデル化した考え方を当てはめることは、活動の流れ、すなわちプロセスを理解するのに非常に有効だと感じた。今回の講の最後に登場した「ゲーム理論」は、日常生活やビジネス、あるいは国と国との問題に取り組む際にも使われるため、社会全体をとらえるうえで、かなり実用性の高いベースと自分では考える。これに関して社会学者が不安を持つ点に疑問が残ったので、学習の中で深めていきたい。

**Comment by yadoiwa** [comment]
# 宿岩芽梨香　グループ2
# 要約
社会学は研究対象がさまざまであるため共通した１つの理論というものがなく、似通ってはいるが基本的には独立した別々の理論がたくさんある。
#### 経済学における標準化された理論
研究法や理論構築における、基本的な発想の仕方は方法論的個人主義と呼ばれるもので、社会を個人の集まりと考えて理論を作る。その分析対象とする個人を合理的経済人としてモデル化する。
#### 社会学に影響を与える経済学のモデル
モデルとは思考実験としての理論において検証するために作られた、研究対象の概念的な模型である。理論経済学では、単純な前提から出発して、モデルの組み合わせによって複雑な社会システムの動きを理解しようとする。一方で、社会学は、膨大な前提を置いたうえで、比較的シンプルな結論を導き出す。経済学のモデルでは活動の主体が人間や企業、家計であり、模倣、学習、コミュニケーションを通じて知識や情報が広がっていてこの合理的主体モデルは社会学にも影響を与える。
ただし社会学において部分には有用であるが基礎づけはできないと、多くの社会学者は考える。では、どのように合理的主体モデルに対抗馬をぶつけてきたのだろうか。
# 感想
ロボットを例にしてモデルについて説明されていてわかりやすかった。理論経済学と社会学は出発する前提も結論を導き出すプロセスもほぼ真逆なのに経済学のモデルが社会学に大きく影響するというのはとても興味深い。しかし合理的主体モデルを基礎づけできないと考える社会学者が多くいるのはなぜか次回の講義で学びたい。

**Comment by Rinne614** [comment]
# 小林凜音　グループ2
# 要約

**古典**
基礎理論や一般理論がない社会学だが、社会学者が共通して認知することがデュルケムやウェーバーのご先祖としてのものであり、そこから社会学者が共有する「常識」を理解して、社会学者が連帯感を持つ理由を理解しようとする。

**経済学の科学方法論**
・経済学の発想の仕方は、社会学者によって「方法論的個人主義」と呼ばれる。
・社会を「個人の集まり」としている。
・社会を理解するには、基本的には個人の行動原理を理解していればいいという立場にある。
・経済学では分析対象とする個人を「合理的経済人」としてモデル化している。

**「モデル」について**
・モデルとは、「思考実験としての理論においていじるために作られた研究対象の概念的な模型」である。
・ゲームは、コンピュータのシミュレーションによって行われる思考実験ともいえる。

**経済学のモデル（戦争ゲームとの対比）**
戦争ゲームでは、膨大な前提を置いたうえで、シンプルな結論を導き出す。理論経済学では、非常に単純な前提を置いたうえで、複雑な社会システムの動きを理解しようとする。社会学者は戦争ゲームに類似している。

**「合理的経済人」モデルの「合理的」**
「合理的」とは、会社が手持ちの人手や設備をできる限り効率よく使って商品を生産するべく頑張ることから、利益を得るために合理的に行動するように仕向けられているということである。（無自覚な合理性）

**合理性と生物進化のロボットモデル**
・経済学は無自覚な合理性の考え方を「自然選択」のアイディアから引き継いでいる。
・生物の個体＝ロボット（遺伝子の乗り物）　プログラム＝遺伝子
・繁殖によって他の遺伝子を混ぜた新しいロボット、突然変異のロボットも生まれうる。

**ロボットモデルの拡張（経済学へ）**
・生物個体＝人間、企業、会計（経済活動の主体）
・遺伝子＝知識、情報（知識の普及は、ライバルのやり方を研究し、真似ることによっておこる。）
・繁殖＝模倣、学習、コミュニケーション

**合理的主体モデルとゲーム理論**
・社会科学全体で大きく影響を及ぼしているが、社会学者内では賛否両論あり。
・経済学の合理的主体モデルを一般化して、社会現象を合理的主体同士の相互作用として分析するのが、「ゲーム理論」

# 感想
ロボットモデルによって経済学で見ていく社会の動向や仕組み、経済学が「合理的経済人」モデルを使用する理由が理解しやすいなと感じた。社会科学内で普及するゲーム理論や合理的主体モデルを簡単に甘受しようとしないような社会学の特性を、引き続き読み進めて学んでいきたいと感じた。

**Comment by amanemasuda** [comment]
# 増田普音　グループ1
# 要約

### 社会学における理論の不明確さ
- 基本的な入口やみんなが共有する研究対象がない社会学では、古典を読むことで常識や相場を理解するように教えられる。
- 似通ってはいるものの基本的には独立した理論が多くある。
### モデル
- 方法論的個人主義により、社会を理解するには基本的に個人の行動原理を理解すればよく、社会秩序は多くの個人の行動の組み合わせとして理解可能、という立場をとる。
- 分析対象とする個人をモデル化する。
- モデル化することでコンピューターを使ったシミュレーション実験を行うことができる。
### 経済学のモデル
- 例えば戦争ゲームは役割があらかじめ分担され、新しい役割を得ることはないが、経済学は単純な前提から出発して複雑な社会システムを理解しようとする。
- 社会学者の発想は戦争ゲームのほうに近い。
- 合理的経済人→利益を得るために合理的に行動し、試行錯誤をしていくうちに効率的な行動を身に着けていく
### 生物進化
- 生物は繁殖していく中で試行錯誤を繰り返している。
- 生物一匹一匹がロボットとしてみなされ、それを動かすプログラムとして遺伝子がある、とモデル化される考え方もある。
### ロボット・モデルの拡張
- 遺伝子が知識と情報、生殖が模倣や学習やコミュニケーションに置き換えられるように、生物進化モデルは経済のモデルへ早変わりできる。
- 合理的主体モデルを経済学的文脈から独立させて一般化し、社会現象絵を合理的主体同士の相互作用として分析する枠組みである、ゲーム理論は経済学以外の学問にも影響を及ぼしている。

# 感想
モデルとは何でモデル化することでどうなるかが分かった。また、モデルをゲームと対比させたり、ロボットとみなして考えることで分かりやすく、より理解が深まったと思う。

**Comment by aisaaaaa** [comment]
# 橋本愛沙　グループ１
# 要約
### 理論の多様化がもたらす古典への回帰
社会学には明確な入口もなく、「基礎理論」「一般理論」と呼びうるものもない
社会学者の理論は互いに似通っているが基本的には独立している
社会学において共有する研究対象はない(何でも当てはまってしまう)
→古典を読むことで社会学の間の「常識」や「相場」を理解

### 「モデル」を用いた考え方　 Ex)経済学
モデル＝模型　⇔　コンピュータのシミュレーション　⇔　理論＝「思考実験」
ここでいう「モデル」とは、「思考実験としての理論においてさまざまに操るために作られた、研究対象の概念的な模型」のこと

### 経済学のモデル(戦争ゲームとの対比)　
自分の利益を増やすために可能な限りの最善を尽くす性向を「合理的経済人」と呼ぶ
→経済学ではこの1種類のみをモデルとする
戦争ゲーム：膨大な前提で比較的シンプルな結論を導き出す　⇒社会学者の発想
理論経済学：単純な前提の組み合わせで複雑な社会システムの動きを理解

### 生物進化と「合理性」の共通点
同じ環境の中で競争し、環境への適応性、効率的な行動の仕方を身に着けたものが勝ち残る

### ロボット・モデルの経済学への拡張
ロボット：経済活動の主体としての人間、企業などの組織
遺伝子(プログラム)：経済的に有用な情報
繁殖：模倣、学習、コミュニケーション

### 「ゲーム理論」
→経済学が発展させた合理的主体モデルを独立、一般化し社会現象を合理的主体同士の相互作用として分析する枠組み
部分的には有用で社会学に大きな影響を与えているが、社会学全体の基礎づけは不可能


# 感想
私は高校時代世界史を選択し世界の様々な地域の歴史や規律、ものの見方を勉強していたが故にそれをうまく経済学に生かしきれない、人々の多様性を描き出せないという短所を持ち合わせている「合理的経済人」のモデルがとても興味深かった。

**Comment by MioAkiyama0223** [comment]
# 秋山美桜　グループ２
# 要約
**社会学とその他の学問との対比**
自然科学において個別な研究は多様であっても共通の入り口が存在している。これは、社会科学・経済学においてもおおよそ共通していることである。これに対し、社会学は明確な入口が存在していない。また、自然科学・経済学は現代の書物を利用し、社会学は現代的なものよりは古代の書物を利用する。古代の書物を読むことで、社会学の共通の祖先から共有している「常識」や「相場」がわかるということである。

**経済学におけるモデル化**
経済学における標準化された理論を社会学者は「方法論的個人主義」と呼んでいる。それは、社会の集まりを「個人」として捉え、秩序を大勢の個性の行動の組み合わせとして理解する立場をとる。そして、分析対象とする個人を「合理的経済人」としてモデル化するのである。例としてシミュレーションゲームが挙げられる。

社会科学の理論もシミュレーションゲームを用いて同じように考えることができ、中でも理論経済学は、非常に簡単な前提から始め組み合わせにより複雑な社会システムを理解しようとするゲームである。対比として膨大な前提を用いたうえでシンプルな結論を出そうとするのが戦争ゲームである。社会学は、理論経済学よりも戦争ゲームのほうがより考えが近い。

**生物学におけるモデル化、そしてその応用**
生物学では、生物の個体を一種のロボットとしてみなしそれを動かすプログラムを遺伝子としてモデル化する。経済学では、これらをそれぞれ置き換えてかんがえることができる。

**「合理的主体モデル」の影響、社会学への利用**
経済学での「合理的主体モデル」は経済・経営・心理・生物・政治学に大きな影響を及ぼしている。これには、社会学も含まれる。しかし、社会学者は「合理的主体モデル」の考え方では社会学全体を基礎づけることはできないと考えている。

# 感想
様々な学問がそれぞれモデル化して考えられることを知り、とても興味深く面白く感じました。また、今回の内容で生物学のモデルを異なる学問である経済学が置き換えて考えることができることを学びました。そこで、置き換え可能な経済学のモデルであっても社会学全体の基礎付けにはできないと書いてあったため、いったい何が社会学の基礎となるのか引き続き考えながら学んでいきたいと思います。

**Comment by mi513** [comment]
# 大島美怜　グループ２
# 要約
#### 社会学の理論の現状
・それぞれの理論に似通っている部分はあるけど基本的には独立した別々の理論が存在している

#### 経済学の考え方とモデル
・社会を理解するには個人を理解していればよいという考え方を「方法論的個人主義」という
・分析対象とする個人を「合理的経済人」としてモデル化する
・モデルとは模型を作っていじってみるという「思考実験」をするために作られた研究対象の模型
・「思考実験」＝「図上実験」

#### 戦争ゲームとの対比
・戦争ゲームは最初から設定がきちんとあったうえで比較的簡単に結論を導き出そうとする
・理論経済学は単純な設定から出発して組み合わせによって複雑なシステムの動きを理解しようとする
・社会学者の発想は戦争ゲームに近い

経済学の主張
・経済において金儲けは重要な目標の一つであり単純な数字で表現できるとモデルとして表しやすい
・利益を得るために合理的に行動するように仕向けられている

#### 生物進化とロボット
・生物の進化やロボットにおいても合理性が利用されている

#### ロボットモデルの拡張
・生物個体＝活動の主体に対応するのが人間、企業、家計
・遺伝子、遺伝情報＝知識、情報

#### ゲーム理論
・経済学が発達させた合理的主体モデルを経済学的文脈から切り離して一般化し、社会現象を合理的主体同士の相互作用として分析する枠組み
・ゲーム理論は他の分野にも影響を及ぼしている
→影響を与えているが社会学者たちはこの理論について疑問を抱いている

# 感想
モデル化して考えることによってより分かりやすかったように感じた。これだけいろいろな話をしても社会学者が「合理的主体モデル」に納得していないようなのでどのような不満があったのか早く知りたいと思った。

**Comment by HirotoGoto** [comment]
# 後藤洸登　グループ１
# 要約
#### 社会学において古典が学ばれる理由
　社会学はほかの学問に比べて理論が多様化しているため、多様化する以前の理論を読めば社会学の「常識」や「相場」が理解できる、として古典を読むことを勧められるケースが多い。

#### 経済学と「モデル」の概念
　経済学は社会を「個人」の集まりを意味する名称に過ぎないとする。そのため、個人の行動原理を理解することで社会全体を理解できる、という立場を取る。この発想を「方法論的個人主義」と呼ぶ。
　また、経済学のもう一つの特徴に個人を「合理的経済人」としてモデル化する、という点が挙げられる。モデルとは実験や思考実験を行う際に使う模型のようなものである。

#### 戦争ゲームと経済学との「モデル」の違い
　戦争ゲームは膨大な、緻密な設定をもとに一つ一つの駒が動き、最終的にはどうすれば勝てるのか、などといったシンプルな結論を導き出す。それとは異なり、経済学では;::/::/単純な前提から始めることで、複雑な社会のシステムを理解しようとする。

#### 生物進化とロボット
　生物の進化は繁殖の中で試行錯誤を繰り返したのち、進化を遂げる。そのため、生物１匹１匹をロボットととらえ、それを動かすためのプログラムとして遺伝子が存在する、という考え方がある。

#### ゲーム理論
　経済学が発達させた合理的主体モデルを一般化し、社会現象を合理的主体同士の相互作用としてとらえようという理論。これは社会学を含めた他の学問にも影響を及ぼしているが、社会学者たちはこの理論では社会学全体の基礎付けは不可能だと考える。

# 感想
　前回よりも一歩踏み込んだ内容だと感じた。「合理的経済人」の捉え方が新鮮で印象深かったものの、やはり人をそこまで合理化したもの、と考えるのには疑念が残った。

**Comment by shofukurono** [comment]
# 袋野奨　グループ２

# 要約
* 「モデルという考え方」
経済学における研究法や理論構築における基本的な発想の仕方が方法論的個人主義といわれる。
社会を個人の集まりだととらえるため社会を理解するには個人を理解しなければならない。
経済学では分析対象とする個人を合理的経済人としてモデル化する。
モデル化とは？
⇒思考実験としての理論においていじくりまわすためだけに作られた研究対象の概念的な模型にすること。

  飛行機を作るときは模型を使ったりして壊れるのが前提で実験する。しかし、理論は思考実験。
  思考実験---コンピューターシミュレーション---模型を使って行う実験

* 「経済学のモデル」
社会学者の発想は、経済学のゲーム論的なものではなく、戦争ゲームのように勝負に勝つといった大前提のもと、比較的シンプルな結論を導き出そうというものに近い。

* 生物進化とアナロジー
生物学的に、生物の個体１匹１匹、ひとつひとつをロボットとみなし、ロボットを動かすプログラムとして遺伝子があるとモデル化される。
現代のダーヴィニズムではロボットたちはプログラムの乗り物であるとされている。

* ロボット・モデルの拡張
経済活動の主体（企業や家計、個人）＝ロボット
プログラム＝知識や情報
⇒経済活動の主体（企業や家計、個人）は知識や情報の乗り物である。
これらは基本的に模倣、学習、コミュニケーションを通して広がる。



# 感想
生物学と経済学の考え方をロボットやプログラムという言葉を使ってリンクさせていたのがわかりやすかった。
様々な学問の話が出てきていて面白かった。

**Comment by 21022163** [comment]
# 権田晴香　グループ１
# 要約
**1.社会学の理論**
・共通かつ明確な入り口がない。
・同じ一つの理論に対して独自の解釈でバリエーションをつけているというより、互いに似通っているが、基本的には独立した理論が沢山ある。

**2.モデルとはーex経済学**
・経済学では支配的な科学方法論は「方法論的個人主義」と呼ばれ、社会を個人の集まりと考え、便宜的につけられた名前以上のものでは無いと考える。
・分析時に、個人を「合理的経済人」と捉え、モデル化する。
・モデル化のモデルとは、思考実験としての理論においていじくり回すために作られた、研究対象の概念的な模型のこと。

**3.理論経済学のモデルー戦争ゲームとの対比**
・戦争ゲーム：膨大な前提の上で、比較的シンプルな結論を導き出そうとする。（社会学はこっちに近い）
　理論経済学：単純な前提から組み合わせにより複雑な社会の動きを理解しようとする。

**4.生物進化**
・生き物たちは繁殖プロセスの中で、集団的な試行錯誤を繰り返す。
・無自覚な合理性の考え方は、経済学でも生物学でも適用される。

**5.ロボット・モデルの拡張**
・繁殖するロボットモデルを生物進化モデルから経済のモデルに進化するときの必要なもの
　生物主体→経済活動の主体としての人間
　遺伝子・遺伝情報→知識情報
・知識情報は模倣、学習、コミュニケーションを通して広がる。

# 感想
前回より、詳しく掘り下げられていて、少し難しい部分があった。要約するとき、何が一番伝えたいことなのかもっと要点をうまく絞れるようになりたい。

**Comment by wakabamomii** [comment]
# 籾井若葉　グループ１
# 要約
**社会学と他の学問の違い**
自然科学において個別の研究は様々であるが、共通の入り口はとてもはっきりしている。これについては経済学も同じようなことが言える。しかし、第１講でもあったように「基礎理論」や「一般理論」がない社会学においては明確な入り口が存在しておらず、みんなが共有する研究対象が無い。そこで、古典を読むことで社会学者たちが共有している「常識」や「相場」が分かる。

**経済学におけるモデル**
経済学者は「社会＝個人の集まり」と捉えており、社会を理解するためには個人の行動原理を理解していればよいと考える。
→このような発想は「方法論的個人主義」と呼ばれる。
経済学では、分析対象とする個人を合理的経済人としてモデル化する。
「モデル」＝いじくりまわすために作られた、研究対象の概念的な模型

**戦争ゲームとの比較**
戦争ゲーム→膨大な前提を置いた上で比較的シンプルな結論を導き出そうとする
理論経済学→非常に単純な前提から出発して、その組み合わせにより複雑な社会システムの動きを理解しようとする。
社会学者の発想は戦争ゲームの方に近いと言える。

**合理的経済人モデルへの疑問**
1.人間はそんなに合理的ではない（行動するたびに自分への損得を考える訳では無い）
2.人間は経済的な損得勘定だけで動いている生き物ではない（感情に従うこともある）
3.人間は皆一緒ではない（生き方や暮らし方は様々であり、多様性がある)

**ロボット・モデルの拡張**
生物個体：経済活動の主体（企業や会計）
遺伝子・遺伝子情報：知識や情報
生殖・繁殖：模倣や学習、コミュニケーション
「ゲーム理論」→経済学が発展させた合理的主体モデルを経済学的文脈から独立させて一般化し、社会現象を合理的主体同士の相互作用として分析する枠組みのこと

# 感想
前回よりも理解するのが難しいと感じることが多かったが、モデルとは何なのか、モデル化するというのはどういうことなのか詳しく学ぶことができた。ゲームと比較することによって身近に感じることができ、より理解が深まった。合理的主体モデルについて社会学者がどのように考えてきたのか、次回詳しく知りたいと思った。

**Comment by AyariNomura** [comment]
# 野村彩莉　グループ１
# 要約
　自然科学と同じように雑多な研究の共通の入り口がはっきりしている経済学とは違って、似通っているが独立した理論がたくさんある社会学は古典を読むことで社会学者が共有している「常識」と「相場」がわかるため、古典を読めと指導される。経済学において、社会を理解するために個人の行動原理を理解してさえすればいいという考え方を「方法論的個人主義」と呼び、分析対象とする個人を「合理的経済人」としてモデル化する。これに対し、理論は研究対象の概念的な模型である「モデル」を頭の中などでいじってみるという「思考実験」であり、中間に位置するのがシミュレーションである。社会科学についてもシミュレーションゲームと関連させることができ、社会学者の発想は前提から比較的シンプルな結論を導き出そうとする戦争ゲームに近い。生物学においては、生物の個体一つ一つをロボットとみなし、動かすプログラムとして遺伝子があるとモデル化する。これは、ロボットを「経済活動の主体としての人間」、遺伝子を「知識」「情報」に置き換えることができる。異なる点として、生物の世界では遺伝を通して知識情報を伝えるのに対し、経済においては模倣、学習、コミュニケーションを通して知識や情報が広がる。

# 感想
社会学だけでなく他の学問との比較を通してより深く理解することが出来たように思う。

**Comment by SayakaFujikawa** [comment]
# 要約
　明確な入口がない社会学には共通理論や基礎理論がないため、社会学者は古典を読んで祖先かた共通している「常識」や「相場」を理解している。
　社会学者は経済学の発想の仕方を「方法論的個人主義」と呼ぶ。経済学は社会を個人の集まりとして捉えているため、社会全体を理解するためには個人の行動を理解すればよいとしている。その個人を合理的経済人としてモデル化して考えている。
　経済学のモデルは無自覚な合理性によって効率よく資源を使って商品を生産するため、合理的経済人と呼ばれている。(これは生物学の自然選択の考えを引いている。)このように経済学は合理的経済人のような単純な前提の組み合わせで複雑な社会学システムを理解しようとする特徴がある。反対に社会学は膨大な前提をもとにしてシンプルな結論を導き出す。この点において社会学は戦争ゲームに似ている。この合理的主体モデルは他の学問、もちろん社会学にも影響を及ぼしている。しかし社会学者はこの理論によって社会学の共通の基礎づけをできるかについては疑問を抱いている。

# 感想
さまざまな学問に話を広げながらの説明やロボットの例がわかりやすくて読んでいて興味深かった。
前回の学習で経済学や社会学には共通する部分が見えるが今回の学習で異なる点の方が目についたような気がした。
よく聞くゲーム理論についても学習することができてよかった。

**Comment by seshitamayu** [comment]
# 瀬下茉由　グループ２
# 要約
### 古典
自然科学においては学問の基本の入り口というものが存在するのに対し、社会学や政治学ではそういった基本の入り口が存在しないため、多く場合古典を読み、社会学者たちが共有している「常識」や「相場」を理解するようにと言われている。
### 「モデル」という考え方
ここで言う「モデル」とは「模型」のようなものを表していて、飛行機などの物理的な実験を表す。
それに対し、理論とは「思考実験」のようなもので、研究対象の概念的な模型がここで言う「モデル」である。
ここしばらくの間にこの二つの間にコンピューターを使った「シミュレーション」が登場してきている。
### 経済学のモデル　(ここでは戦争ゲームとの対比)
戦争ゲームで膨大な前提を置いた上で比較的シンプルな結論を導き出す。(社会学はこちらに近い)
それに対し、経済学では単純な前提から複雑な社会システムの動きを理解しようとする。
### 生物進化とロボット
生物が集団的な試行錯誤を繰り返し、生物の個体一匹一匹、一つ一つを一種のロボットと見なし、遺伝子の乗り物としてプログラムがあるのと同じように、経済学では主体となる企業や個人は有益な知識・情報の「乗り物」である。
経済社会における有益な情報の普及は模倣・学習・コミュニケーションによって行われている。


# 感想
第一講よりも複雑で理解し難く感じ、特に後半の生物進化やロボットの話は難しく感じた。
しかし、社会学と同時に自然科学や経済学についても比較をしながら話が広がっていて、より多くのことを知ることができて良かった。

**Comment by yui423i** [comment]
# 石橋 由衣　グループ2
# 要約
**社会学を学ぶ際の古典の重要性**
社会学は基本的に独立した別々の理論が沢山あるため社会学を学ぶ際、社会学者たちが共有している常識や相場を理解するために現代的な教科書を読むだけでなく必ず古典を読むよういわれている。

**モデル化**
経済学が発達させた合理的主体モデルは社会科学全般に対して大いに影響を及ぼしている。
合理的主体モデルを経済学的文脈から独立させて一般化し、社会現象を合理的主体同士の相互作用として分析する枠組みである「ゲーム理論」は経済学だけではなく社会学や経営学、政治学、生物学などにも大きな影響を及ぼしている。
理論の標準化が進んでいるという意味で、社会科学全般の中で自然科学に比較的に近いとされている分野が経済学である。
経済学における基本的な発想の仕方は「方法論的個人主義」と呼ばれている。そして経済学では分析対象とする個人を合理的経済人としてモデル化する。モデル化して考えると社会科学の理論一般もシミュレーション・ゲームを手掛かりに考えることができる。
理論経済学では単純な前提から始まり、その組み合わせによって複雑な社会システムの動きを理解しようとするが、一方で社会学者の発想は戦争ゲームの膨大な前提を置いた上で比較的シンプルな結論を導き出すのである。
しかし社会学者たちはこの合理的主体モデルは部分的には有用であるが、全体の基礎付けはできないと考えている。

# 感想
想像のしやすいゲームという具体例により社会学と経済学の考え方の違いを知ることができた。
名前だけ知っていたゲーム理論だが、これからさらに理解を深めていきたいと思った。

**Comment by Johnsonliusw** [comment]
![image](https://user-images.githubusercontent.com/82936224/117680017-be1dff80-b1eb-11eb-8c6d-a5831d6fd1b3.png)

**Comment by Johnsonliusw** [comment]
![image](https://user-images.githubusercontent.com/82936224/117680175-e4dc3600-b1eb-11eb-94b1-5148a9296a43.png)

**Comment by Johnsonliusw** [comment]
# 要約

**Comment by Johnsonliusw** [comment]
# 劉松蔚　グループ１
# 要約
１、社会学について「古典」のあり方
　他の社会科学と自然科学に対して、古典を読むことは「余裕があったら読みましょう」という概念だが、社会学の場合には、「古典」は社会学者たちが共有している常識と認識している。（政治学は例外、古典を読むが、研究対象が違う）

２、経済学のモデル
・社会学者たちは経済学の研究法を「方法論的個人主義」と呼ぶ。
・この経済学には科学的な分析方法の前提なのは全ての分析対象が「合理的経済人」からだ。（自分の利益を増やすために、可能な限り最善の手を打って行動しようとする人）
・このモデルを支えるのは分析対象を思考実験（図上演習）という考え方だ。
・反論：そもそも人間は不合理な生物で、感情と環境の影響を受けやすく、こうすれば人間の多様性を消す事になるだろう。
・経済学の言い分：合理的、効率的に行動すれば楽ができる一方、非効率的に振る舞っていれば損をし、苦労する人々は試行錯誤で効率的な行動の仕方を身につけていくだろう。

３、進化とモデル進化の可能性
・経済学に「自然選択」の生物学の考えを加えて、文章の中で「ロボット」を例に上り、うまく環境に適応できたものが生き残るという概念が出てくれる。
・経済学にもどる。合理主義で誕生した「ゲーム理論」でも同じ、主体同士の相互作用に分析する新たな枠組みが経済学だけではなく、さらに他の学科に大きな影響を及ぼしている。

# 感想
非常に興味深い！（時間が間に合わないので、簡単に。。。）

**Comment by KarenTakamatsu** [comment]
#  髙松かれん　グループ１
# 要約
**他学問と社会学の理論**

・一般的な学問には「理論科学」という入口が存在し、そこから枝分かれのように細分化されるのだが、社会学には明確な入口がない。
・他学問は学者同士の関心の焦点は一致しているが、社会学は、共通点無し。
・社会学 ＝ 同じ一つの理論に対して独立した個々の理論が存在する。

**「モデル」とは**

・1−1でもあったように実験をする際、
　「社会学」は倫理上などの問題から代わりのものを使用
　「理論」は思考実験として作られた研究対象の概念的な模型を使用　→ 「モデル」
　（例）シュミレーター

**経済学における「モデル」**

・自然科学に近い経済学では、支配的な科学方法論という基本的な発想の仕方を社会学者によっては「方法論的個人主義」と呼ばれる。
・社会とは個人の集まりであり、分析する際その対象になる個人を「合理的経済人」としてモデル化する。
　「合理的経済人」は無個性な性質がある。
・社会学の理論は思考が複雑　⇔　経済学は単純
　つまり、経済学によって、無個性な性質から役割分担を形成する個性が誕生。

**生物進化とロボット**

・生き物は繁殖プロセスの中で集団的な試行錯誤を繰り返している。
・企業間では「知識」と「情報」を持ったものが勝ち残る
　人間界では「コミュニケーション」や「学習」、「模倣」の能力を持っているものが勝ち残る

# 感想
提出し忘れたため、締め切り期限を過ぎてしまいました。
今週担当の籾井若葉さんにも大変ご迷惑をおかけいたしました。
申し訳御座いません。
