### ISSUE TITLE
課題4: 輪読1-3 稲葉 『社会学入門』 第3講 方法論的全体主義 の要約

### ISSUE THREAD

**Issue by yofukami** [icat-lab/ay2021spring_icatlab#5]
# 概要
発表担当者の投稿を踏まえ、[テンプレート](https://github.com/icat-lab/ay2021spring_icatlab/blob/main/templete_issues) にのっとって、輪読課題である　"稲葉 『社会学入門』 第3講 方法論的全体主義"の要約を各自投稿してください。

# 締切
- 5月19日(水)16:20

# 輪読の流れ
[こちら](https://github.com/icat-lab/icat_lab/blob/master/basic_seminar_undergrad/literature_review.md)を参照ください。
今週から手順が改定されているので注意してください。

**Comment by shioriko-tokunaga** [comment]
# 德永栞子　グループ２
# 要約　

**1. 方法的論全体主義とは**

- 分析の基本単位を社会にする立場
- 「holism」→全体を個人の単なる立場に還元することができない立場

**2. 社会に共有されるもの**

- 方法論的社会主義の考え方→物事には社会的に共有された前提が必要になる
- このような現象を成立させる固有の水準とは何か
- 社会＝役割の異なる個体の相互依存ネットワークから成るもの

**3. **社会有機体説とは****　

- 個人が集まってできた生き物「個体」である＝社会＝実体
- 全体主義という恐ろしい結果を引き起こすこともある　
- 「社会」の全体のレベルが曖昧　
- 言語、意味、ルールが固有の対象　

**4. **形式主義****　

- どのような存在でも、知識、情報の担い手として単位は変わらない　

# 感想
少しずつ読み進めていくことで、社会学を考えるときの前提は何なのかが分かってきた。これはのちに、大きな論点としてとらえている「理論」に結びつくのではないかと思う。

**Comment by Rinne614** [comment]
# 小林凜音　グループ２
# 要約

**方法論的全体主義**
・方法論的個人主義の反対。ここでいう全体主義は、holism（＝社会を個人に還元することはできない）ことを表す。
・同義語の方法論的社会主義は、分析の基本単位を個人ではなく社会とする立場をいう。
・ほとんどの社会学者が支持する。

**社会的に共有されるもの**
・演劇モデルから、「台本のように”あらかじめ社会的に共有された前提”が必要になる」と考える。
・あらゆる現象を成り立たせる”固有の水準”がある。
・この”固有の水準”は社会学、社会学者が固有の対象にしたいものである。
・生物学的モデルから、社会は複雑なシステムであるため、この水準の固有性は一人ひとりの個人から作り上げていく考えて
　も理解しにくい。
・固有の対象は実体を持たない。

**社会有機体説**
・個人＝細胞として、社会＝細胞が集まってできた生き物（＝個体）としてとらえる考え方。
・有機体＝勝手に動き回る複雑なシステムのこと。
・社会それ自体を実体だと考える。（方法論的個人主義者では社会は実体を持たないとする。）
・政治的に危険で道徳的に危ない。（全体主義、ファシズム、ナチス、スターリン期のソヴィエトの経験）
・社会全体の「全体」の単位（大きさのレベル）が曖昧。

**ゲームのルールに着目した見解**
・ゲーム内で「意味を持った要素」や「ルール」が固有の対象として人々の間で共有されているとみなす立場。
・一定の意味のある要素を一定のルールにのっとり共同で組み合わせる際に、「言語」を用いる。

**形式主義**
・個人であれ集団であれ「知識・情報」の担い手として質的な単位は変わらない。（全体の単位の問題がない）
・「知識・情報」はコミュニケーション（言語）を通じて流通するが、いまだ言語のメカニズムを見いだせていない問題。

# 感想
社会学が一般的に共有することを探してきたが、今回の章では、社会では「ルール」や意味を持った言葉の「意味」など、人々の間で共有されているものがあり、社会学者が固有の対象にしたいものがあると少しずつ分かってきた。次章でもそういうものを更に知っていけるのではないかと思った。

## 代表者のまとめに対するフィードバック
私も、今回はいろいろなとらえ方によって説明がされていたので難しいと感じましたが、生物学とのアナロジーの部分は前章で出てきていたので理解しやすいと感じることができました。

**Comment by amanemasuda** [comment]
# 増田普音　グループ1

# 要約　　

## 方法論的全体主義
- 「方法論的社会主義」とは社会科学において分析の基本単位を個人ではなく社会とする立場をとる。
- 「方法論的全体主義」における「全体主義」に対応する英語の表現は"holism"である。
- ほとんどの社会学者は、社会＝個人の単なる集まりには還元しきれず、独自のアイデンティティを持っている、と考えている。

## 演劇モデルから考えると
- 「方法論的個人主義」→複雑な演劇でも個人の即興の積み重ねとして組み立てることが可能。
- 対して、「方法論的全体主義」→台本のようにあらかじめ社会的に共有された前提が必要になる。　
- 「ごっこ遊び」と演劇を区別する固有の水準がある。社会学では水準の固有性は、一人ひとりの個人から出発して積み上げただけでは十分理解することはできない。

## 社会有機体説
- 個人を細胞のようなものとして考え、社会とはそれが集まってできた「個体」のようにとらえる。
- 「有機体」→生き物たる「個体」を「モデル」に社会を理解しようとする。
- 社会有機体説は、政治的、道徳的に危険。
- 社会有機体説を真に受けて社会を運営してしまうと、「ファシズム」のような危険な結果を招く。

## 形式主義
- 社会学的な「全体」を「形式」とみなすことは集団と個人の間に質的な断層を想定する必要がなくなるため、社会有機体説のようなアプローチに比べて政治的・道徳的な観点からより安全と言える。
- 形式主義のアプローチにも問題はあるものの、「知識」「情報」の担い手として質的には変わることのない単位とみなされるため科学的にもこちらのほうが安全であるといえる。

# 感想
知らない単語がいくつかあったが、方法論的個人主義と方法論的全体主義、社会有機体説と形式主義については対比して述べられていて理解しやすい部分もあった。

**Comment by MioAkiyama0223** [comment]
# 秋山美桜　グループ２
# 要約
**社会学を支える考え**
経済学を支える「方法論的個人主義」の対語として「方法論的社会主義」や「方法論的全体主義」というものがある。ここでの社会主義というのは、社会科学においての分析の基本単位を個人とするのではなく、社会とする立場をとるものであり、全体主義を英語でいうのなら、totalitarianismではなくholismをさす。
**社会を演劇モデルで例える**
社会を演劇モデルで例えるならば、「方法論的社会主義」はどんな複雑な演劇でも個人の即興の積み重ねとして組み立て、理解すべきという考えに対し「方法論的社会（全体）主義」は台本のようなあらかじめ社会的に共有された前提が必要となる。つまり、社会には、前もって存在する社会的コンテクストがあるということだ。ならば、その社会的コンテクストを成立させる固有の水準とは何か。
**社会有機説、方法論的全体主義の問題点**
固有の対象の捉え方として、社会とは個人を細胞としてそれらが集まってできる「個体」のようなものだという「社会有機説」の考え方がある。これは、社会自体を実体としてみなすものであり、この考えを政治的意味ではない、科学的方法論としての「全体主義」に立つ瀬があるのか考える必要がある。
また、方法論的全体主義の「全体」とは、どこまでを全体とするのかという問題が出てくる。大抵の人間はいくつもの社会的なシステムに属しているが、この中のどれも「全体」として呼ぶべき特権的な社会は見当たらない。
**形式主義としてのアプローチ**
「全体」をどこまでみなすのかという問題に対して「形式主義」のアプローチならば、「知識」「情報」の担い手として社会的システムを質的には変わらないとみなすために有用である。「情報」の担い手としての「遺伝」のメカニズムは、それをつかさどる物質としてDNAがある。「情報」は「言語」を手段としてコミュニケーションをとっているが、「遺伝」にとってのメカニズムがDNAと対応するような具体的対象を「言語」のメカニズムにおいては、見出していないのが現状である。

# 感想
今回は、いつもよりもとても難しく感じました。これまで読んできて、やはり社会学はほかの学問と比べ、研究対象にするものも難しかったり、何かしらの問題点があったりとより複雑な学問であると再認識しました。

# 代表者のまとめに対するフィードバック
私も、今回の話はいろいろな考えが出てきていて、文章を理解しづらく感じました。要約が簡潔にまとめられていてとても読みやすかったです。

**Comment by wakabamomii** [comment]
# 籾井若葉　グループ１
# 要約
**方法論的全体主義とは**
方法論的全体主義→方法論的個人主義と逆の意味を持つ
　　　　　　　　　ここでの「全体主義」の意味は「totalitarianism」ではなく「holism」
似た意味を持つ方法論的社会主義は、社会科学において分析の基本単位を個人ではなく社会とする立場のことを言う
社会学者の考えとしては、社会＝個人の単なる集まりには還元しきれない独自のアイデンティティを持っているもの
「方法論的個人主義」では理解し尽くすことはできないため、「方法論的全体主義」を支持

**演劇モデルを用いた比較**
「方法論的個人主義」→どんなに複雑な演劇でも個人の即興の積み重ねとして組み立てることが可能
「方法論的全体主義」→社会的に共有された前提が必要である（台本など）
社会学者たちが自分たちの固有の対象としたいと考えているもの→固有の水準

**社会有機体説とその危険性**
方法論的個人主義では、社会=個人という実体の集まりではあるが、社会それ自体は実体を持たないと考えられている
それに対して社会有機体説は社会それ自体を実体だと考えている
社会有機体説は「政治的に危険で道徳的に危ない」
→これに基づいて社会を運営してしまうと全体主義やファシズムに繋がる恐れがある

**ゲームのルールに着目する**
一定の意味を持った要素を一定のルールに基づいて共同に組み合わせていく
ゲームの中では意味やルールが関係者同士で共有されている＝「社会学の固有の対象」

**形式主義**
形式主義のアプローチでは「知識」「情報」の担い手の質的には変わるところのない単位とみなされる

# 感想
今回も難しい単語が多く出てきたが、方法論的個人主義と方法論的全体主義の比較の部分などはわかりやすく説明されていたので少しは理解を深められたと思う。

**Comment by yadoiwa** [comment]
# 宿岩芽梨香　グループ2
# 要約
#### 方法論的社会主義
方法論的個人主義の反対概念に、方法論的社会主義、方法論的全体主義がある。方法論的社会主義とは、社会科学において分析の基本単位を個人ではなく社会とする主義である。方法論的社会主義、方法論的全体主義をとる人たちには社会に共通された前提が必要にある。
#### 固有の水準
このような現象を成立させているのは固有の水準である。固有の水準とは、社会学の固有の対象、社会学者たちが自分たちの固有の対象としたいと考えているものである。社会は互いに役割が異なるたくさんの細胞の相互依存のネットワークからなる生物個体と同じように複雑なシステムであり、この水準の固有性は個人から出発して積み上げられただけでは理解できない。
#### 社会有機体説
生物のアナロジーから考えると個人を細胞のようなものだとすると社会はそれが集まってできた生き物、個体である。人々は同じ言葉や文化を共有しながらそれぞれ別の役割を分担して１つのまとまったシステムを形成する、社会学の研究対象は社会という大きな実体であるというこの考え方を社会有機体説という。しかし全体と呼ぶべき社会が１つに定まっていないため社会という複雑な対象を相手にする以上、多種多様な全体を研究するだけでなく、複数の全体同士の関係についても考えたい。
#### 固有の対象
様々な固有の対象の共通した性質は、ある一定の意味を持った要素をある一定のルールにのっとって共同で組み合わせていく作業だということである。一定の意味やルールが共有されて初めて成り立つ相互作用として社会学の固有の対象を理解すべきである。
#### 形式主義
全体を形式とみなす考え方を形式主義という。このアプローチの仕方は、知識や情報の担い手として質的にかわらない単位とみなされるので実体主義より安全である。しかし知識や情報を流通させるコミュニケーションを行うための中心的な手段である言語のメカニズムにおいてわかりやすい具体的な対象を見いだせていないことが問題である。
# 代表者の要約に対するコメント
様々な主義や説が出てきてどの部分が重要な要点かが分かりにくく苦労したが大島さんの要約は演劇などのたとえを用いて箇条書きで簡潔にまとまっていて理解しやすかった。

**Comment by aisaaaaa** [comment]
# 橋本愛沙　グループ１
# 要約
**方法論的個人主義（全体主義）**
分析の基本単位を社会とする
本来の社会主義・全体主義とは意味が異なる
あらかじめ社会的に共有された前提が必要になる

**社会的に共有されるもの**
必ず個人に先行して社会的なコンテクストが先行する（どこかの国に生まれ文化や言語を仕込まれる）が、こうした現象は「個人主義」だと説明しきれない
↓
こうした現象を成立させる固有の水準（＝社会学の固有の対象としたいもの）とは何なのか？

**社会有機体説**
「固有の対象」の捉え方についての１つ目の方向性
個人を細胞のようなものだとすると社会はそれが集まってできた生き物、「個体」のようなものだという考え方
“有機体”とは勝手に動き回る複雑なシステムのこと
「方法論的個人主義」と反対で、社会という大きなボディを社会学の研究対象とする

**社会有機体説の危険性**
Ex)20c半ばまでに経験したファシズム、全体主義（≒社会主義）
社会有機体説を真に受けて社会を運営すると危険な結果を招く

**共同行為を可能にする「意味」や「ルール」**
「固有の対象」の捉え方についての２つ目の方向性
Ex)ゲーム、演劇、音楽
ある一定の意味を持った要素をある一定のルールにのっとって共同で組み合わせていく作業を可能にする「意味」や「ルール」を社会の固有の対象にする

**形式主義の可能性**
社会有機体説　　「全体」を「実体」とみなす
形式主義　　　　「全体」を「形式」とみなす→集団と個人の間に質的な断層を想定しなくてよい
情報の遺伝として「言語」というメカニズムはコミュニケーションを中心的手段としているが、生物学でいうDNAのようなはっきりとわかりやすい具体的な対象を「言語」のメカニズムにおいて見出せていない（存在すらわからない）

# 感想
今回の３講に関しては文章内で曖昧に同じ内容が繰り返されていたり、並列がお互い遠い位置に存在していたり、対立が多用されていたりと読みにくかった部分はあったが、今まで引き延ばされてきた社会学の固有の対象（にしたいもの）の方向性にようやく触れることができて多少なりとも達成感があった。

**Comment by 21022163** [comment]
# 権田晴香　グループ１
# 要約
**1. 方法論的社会(全体)主義とは**

「方法論的個人主義」の対義語。「社会主義」とは政治的な社会思想ではなく、社会科学において分析の基本単位を個人ではなく社会とする考えのこと。(全体主義も同様。)
ほとんどの社会学者は、この方法的社会(全体)主義にシンパシーを抱く。

**2.演劇から考える**

方法論的個人主義→どんなに複雑でも個人の即興の積み重ねとして組み立てる
方法論的社会主義→台本のようにあらかじめ社会的に共有された前提が必要
たとえ即興であったとしても、「前提」というものがある。その「前提」は、社会コンテクストが存在する。そのため、方法論的個人主義では説明しきれないものが出てくる。演劇の即興とごっこ遊びの区別するような「固有の水準」が社会学者が自分たちの固有の対象としたいと考えているものである。

**3.社会有機体説**

社会有機体説→個人を細胞のようなものとすると社会はそれが集まってできた生き物である、という考え方。
(この考えにそえば、社会学の研究対象は社会という大きな実体。)
社会有機体説の危険性→政治的に危険、道徳的に危ない。(ex ファシズム)

**4.形式主義**

実体主義の反対。どれも特別に特権的な存在ではないことがきちんと理論内在的に根拠づけられる。

# 感想
前回で述べられていたことが、方法論的社会主義でより理解できた。固有の水準や、全体の定義など漠然としているものが多いなと感じた。

**Comment by AyariNomura** [comment]
# 野村彩莉　グループ１
# 要約
　経済学における「方法論的個人主義」の対義語として、分析の基本単位を個人ではなく社会とする「方法論的全体主義」がある。社会は個人の集まりには還元しきれない独自のアイデンティティを持っているため「方法論的社会主義」で理解し尽くすことは出来ず、必ず個人に対して社会的なコンテクストが先行している。社会は互いに役割が異なるたくさんの細胞の相互依存のネットワークからなる生物個体と同じように複雑なシステムであり、この水準の固有性は個人から積み上げただけでは理解できないと社会学者は考える。個人を細胞のようなものとすると、社会とはそれが集まって出来た「個体」のようなものだという考え方を「社会有機体説」と呼ぶ。しかし、これは政治的、道徳的危険を秘めている。また、ある一定の意味を持った要素をある一定のルールにのっとって共同で組み合わせていく作業で共有される「意味」や「ルール」を「社会学の固有の対象」とし、全体を形式とみなす考え方を「形式主義」と呼ぶ。このアプローチ方は、「知識」「情報」の担い手として質的に変わらない単位とみなされるために実体主義より安全と思われるが、「知識」「情報」を流通させるコミュニケーションの中心的な手段である「言語」メカニズムにおいて分かりやすい具体的な対象の存在さえ見出していないという難点がある。

# 感想
　第３講まで読んで、社会学の研究をするには様々な課題があるのだなと感じた。

**Comment by KarenTakamatsu** [comment]
# 髙松かれん　グループ１
# 要約
**1. 方法論的全体主義（社会主義）とは**

・「方法論的個人主義」の対義語
・ここでの「社会主義」とは、社会科学において分析の基本単位を個人ではなく社会とする。
・全体主義は全体の利益のために個人の自由や生命はいくらでも犠牲にして良いという考え方。
　ここでは「totalitarianism」ではなく「holism」
・「社会主義」と「全体主義」は完璧なイコールの関係というわけではない。
・現実の社会は独自のアイデンティティを持っているため、個人主義では理解、説明し尽くせない。

**2. 社会に共有されるもの**

・方法論的個人主義は、どんなに複雑でも個人の即興の積み重ねとして組み立て可能
・方法論的全体主義（社会主義）は、単なる個人で理解するには無理があるため、あらかじめ共有された前提が必要

**3. 社会有機体説とその危険性**

・「社会有機体説」とは、個人を細胞のようなものとすると社会とはそれが集まってできた生き物、個体のようなものだという考え方。
・社会有機体説に基づいて社会を運営してしまうととんでもない危険性を招く
・政治的、道徳的に危険（例）ナチス・ファシズム

4. 形式主義

・「全体」と呼ぶべき特権的な社会は見当たらない
・個人や集団でも「知識」「情報」の担い手としての質的な単位は変わらない
・「知識」「情報」を通じて流通するが、いまだに言語のメカニズムを見出せていないのが問題。

# 感想
今回の内容はとても難しく理解するのが難しかったのですが、他の方々の要約を参考に文章を読み進めて行ったら理解度が少し深まりました。

**Comment by SayakaFujikawa** [comment]
# 藤川紗亜花　グループ１
# 要約
**方法論的全体主義とは**
ここでいう全体主義は、いわゆる"totalitarianism"という意味での全体主義ではなく、"holism"という意味に対応する全体主義―分析の単位を社会、全体とするという立場のことであり、ほとんどの社会学者はこうした方法論的全体主義に、社会を単なる個人の集まりとして捉えるべきでないとして、シンパシーを抱いている。
社会的に共有されるもの
方法論的個人主義を、単純な即興の遊び、つまり子どものごっこ遊びに適応すると、方法論的社会主義は一人ひとりに決められた役割があり、台本に基づいて演技をする演劇と考えられる。しかし社会に生きる人々は、生まれた場所の言葉や文化、生活習慣などがあらかじめ仕込まれていて、なんらかの「役割」をすでに与えられているということから、社会学者の多くは方法論的社会主義を支持する。
**社会有機説**
固有の対象を単純に捉えるときに個人を同じ遺伝子、（ここでは同じ言語、文化などを共有していること）を持ち特殊化した細胞として捉え、それぞれの役割を果たして社会という個体を作り上げていると考えるのが社会有機説である。
しかしこのような考えは結果的に個人を社会の一部分とみなす考えにつながりかねない。それによって「全体主義（いわゆる"totalitarianism"）」や「ファシズム」を再び生み出す可能性がある。
社会学で固有の対象とするもの
社会学における固有の対象をどの単位とするかが大きな論点だが、ここでは、関係する人々の間で、一定の意味やルールが共有されていて初めて成り立つ「相互行為」、またはその「意味やルール」を固有対象とする。
**形式主義の可能性と課題**
個人と社会の質的な違いを考慮する必要がなくなったことで、政治的、道徳的に安全と言える。科学的な観点で見ても、今まで述べてきたような固有の対象の違いによる質的な違いはないと理論づけられるため、少しばかり安全と言える。
生命現象の世界での情報の担い手は「遺伝」で、それをつかさどるDNAは特権的な存在感を持つ。
社会学の中では知識や情報の担い手は「言語」で、人々は主に「言語」を使ってコミュニケーションを図る。
しかし、「遺伝」のメカニズムにおける「DNA」のような特権的なものを「言語」のメカニズムの中からまだ見いだせていないのが現状である。
# 感想
形式主義の部分が一番理解しにくかったが他はいつものように例をたくさん用いて説明してあったので理解しやすかった。今回も生物学に結び付けていたため、まったく異なるように見える学問で社会学を説明しているのが面白かった。

**Comment by shofukurono** [comment]
# 袋野奨　グループ２

# 要約
* 方法論的全体主義とは
方法論的個人主義の対義語、社会科学において分析の基本単位を個人ではなく社会とする立場のこと。
ほとんどの社会学者は社会を方法論的個人主義で理解しつくすことはできないと考えている。圧倒的多数の社会学者が何らかの意味で方法論的社会/全体主義をとる。
* 社会有機体説とは
社会有機体説とは、たくさんの細胞があつまってひとつの個体ができるのと同じように個人が集まって社会ができるという考え方。
* 社会有機体説の危険性
アウシュヴィッツのユダヤ人虐殺やスターリン体制による大量粛清のような「個人は社会という全体の一部でしかない」とわりきった全体主義に基づく政治体制が危険を冒していたという歴史的経験がある。よって政治的に危険で道徳的に危ないという結論に20世紀後半に達したてしまった。だが、科学的方法論としての全体主義は考えようがある。
* 形式主義
どの単位を全体ととらえればよいかわからない場合は形式主義のアプローチなら、根拠づけられる。
だが、形式主義の問題点は、知識や情報の伝達手段として、言語と遺伝があるが遺伝のメカニズムでのＤＮＡ
DＮＡに対応するようなわかりやすい具体的対象を言語のメカニズムで見出していないこと。

# 感想
３講まで読み進めていくと前に出てきたたとえや事柄と比較して述べられていたりするので読んできたところを理解し、これから読んでいくところも理解し続けていく必要があると思った。

# 代表者のまとめに対するフィードバック
キーワードかしっかり抜きだしてあってわかりやすかった。

**Comment by seshitamayu** [comment]
# 瀬下茉由　グループ２
# 要約

### 方法論的全体主義
・方法論的全体主義の「全体主義」に対応する英語の表現は¨holism¨である。
・社会学者は、社会が個人の単なる集まりには還元しきれない、独自のアイデンティティを持っていると考えている。
### 社会的に共有されるもの
・方法論的個人主義は個人の即興の積み重ねが可能である
・方法論的社会主義、方法論的全体主義は社会的に共有された前提が必要になる。


### 社会有機体説
・「社会有機体説」とは、個人を細胞のようなものとしたとき、社会はそれらが集まってできた生き物「個体」のようなものだとする考え方。
・社会有機体説では社会自体を実体だと考える。
・一方、方法論的個人主義は社会は個人という実体の集まりであり、社会それ自体は実体を持たない名前に過ぎないと考える

### 社会有機体説の危険性
・社会的有機体説を真に受けた政治体制にしてしまうと、「全体主義」「ファシズム」の危機に陥ってしまう。
・「全体主義」と方法論としての「全体主義」は別だとは言え、重なるものがあるため、方法論的全体主義にも危険は潜んでいる。

### 形式主義
・全体を形式とみなす考え方を形式主義という。
・個人も集団も知識、意味、情報の担い手として質的な断層を想定する必要がないため、政治的、道徳的観点から安全といえる。
・「遺伝」のメカニズムにとってのDNAに対応するような具体的な対象を「言語」のメカニズムにおいて見出していない。

# 感想
最後の形式主義の部分が難しかった。しかし方法論的個人主義との対比やその他の様々な例が使われていたので、比較的わかりやすい部分もあった。
次回は、今回理解しきれなかった「形式」について理解を深めたい。

# 代表者のまとめに対するフィードバック
大島さんの要約は、私が自分で要約する際にはまとめきれなかった様々な例も箇条書きにしてまとめていたので、わかりやすかった。

**Comment by yui423i** [comment]
# 石橋由衣
# 要約

**方法論的全体主義**
方法論的個人主義の反対概念として方法論的社会主義、方法論的全体主義という言葉がある。
社会科学において分析する基本単位を個人てはなく社会としている。社会学者は方法論的個人主義で社会を理解し尽くすことはできず、個人の単なる集まりには還元しきれない独自のアイデンティティを持っていると考えている。
又方法論的社会主義をとる人たちは台本のようにあらかじめ社会的に共有された前提が必要になると考えている。

**社会有機体説**
社会学の固有の対象というものは具体的に触れる実体を持たず、抽象的で曖昧である。固有の対象の捉え方として、社会とは個人を細胞のようなものとするとそれらが集まってできた生き物、個体のようなものだという考え方である、社会有機体説がある。
社会有機体説に従えば、個人も社会も実体であると考える。
しかし社会有機体説の考え方は政治的に危険で道徳的に危ないという結論に20世紀半ばにたどり着いてしまった。

**形式主義**
実体主義との対比でいう形式主義のアプローチであれば個人や家族や企業や国家でも知識、情報の担い手として質的には変わるところのない単位とみなされるため、どれも特別に特権の存在ではないことが理論内在的に根拠づけられる。
しかし言語というメカニズムをコミュニケーションの主な手段として使用してるが、言語と遺伝のメカニズムは似ているものでも遺伝のメカニズムにとってのDNAに対応するようなわかりやすい具体的な対象を言語のメカニズムにおいては見出していない。

# 感想
さらに内容が難しく感じましたが、要約がわかりやすく理解を深めることができました。

形式主義についての理解をもう少し噛み砕いて理解したいと思いました。又文章内で比較していることでよりわかりやすくなっていると感じました。

**Comment by Johnsonliusw** [comment]
# 劉松蔚　グループ１
# 要約
１、「方法論的全体主義」
・定義：全体の利益のために個人の自由や生命はいくらでも犠牲にしてよいという考え方。
その前提として：一人一人の個人は必ず社会的なコンテクストが先行しているわけだ。
・方法論の個人主義に対しての疑問：互いに役割が異なる細胞の相互依存のネットワークからなる生物個体と同じように、複雑なシステムを単純化して考えると、方法論的個人主義がほんとにいいのか。
２、「社会有機体説」
・定義：個人を細胞のようなものとすると、社会とはそれが集まってできた生き物、「個人」のようなものだという考え方。方法論の個人主義と違い、社会有機体説は、社会それ自体は実体とみなす。
・問題：全体主義とファシズム主義のような結果を招く。
・注意点：事前に＜対象確定＞、＜規則設定＞を決めていないと、分析できない。
３、「形式主義」
・定義：社会的な＜全体＞（知識、意味、情報）を＜形式＞とみなすアプローチと言える。社会有機体説と対比して、より優れている、より健全である。
・問題：＜言語＞のメカニズムには見出せていない。
