### ISSUE TITLE
課題5: 輪読1-4 稲葉 『社会学入門』 第4講 社会学は何を対象とするか の要約

### ISSUE THREAD

**Issue by yofukami** [icat-lab/ay2021spring_icatlab#9]
# 概要
発表担当者の投稿を踏まえ、[テンプレート](https://github.com/icat-lab/ay2021spring_icatlab/blob/main/templete_issues) にのっとって、輪読課題である　"稲葉 『社会学入門』 第4講 社会学は何を対象とするか"の要約を各自投稿してください。

# 締切
- 5月26日(水)16:20

# 輪読の流れ
[こちら](https://github.com/icat-lab/icat_lab/blob/master/basic_seminar_undergrad/literature_review.md)を参照ください。
今週から手順が改定されているので注意してください。

**Comment by shioriko-tokunaga** [comment]
# 德永栞子　グループ２
# 要約

**1. 「形式」の考え方**

- 個体　individual（一つ一つ切り離されていて、別々に数えられる）
→自分と外の世界を区切る境界線を持つもの

**Comment by shioriko-tokunaga** [comment]
# 德永栞子　グループ２
# 要約

**1. 「形式」の考え方**

- 個体-individual-を形成するもの（切り離されて、数えられる）
→自分と外の世界とを区切る境界線を持つもの、「形」がある　ex）生物は「身体」の形を保っている　
- 「内容」「実質」＝形を与えられる素材、素材が集まった「形」＝「形式」　

**2. 形式主義を人間、社会学に当てはめる**　

- ヒトを素材に、社会的に共有された知識や情報（形式）を取り込み、社会的な存在としての「人間」になる　
- 学習やコミュニケーションによって得た知識、振る舞い、言語などを広い意味で「文化」と呼ぶ
- 社会学と（文化）人類学は少し似ている（対象のフィールドの交差）　

**3. 文化のダイナミズム～コンピューターモデルから考える～**　

- コンピューターのコンピューター以前の機械との違い→「万能機械」であること
- ハードウェア（物理的な機械）とソフトウェア（プログラム）が分離している　
- 「計算」＝「形式」の操作であれば、どんな操作も可能　

**4. ハードウェアとソフトウェアの分離**　

- 伝統的な機械（本来の機能を果たし、特定の仕事をするための機械）はハードウェアとソフトウェアの分離がない
→脳となる部分と動力になる部分を一体化して考える　
- コンピューター→道具としての働き、機能はソフトウェアにかかっている　

**5. コンピューターと人間のモデルのアナロジー**　

- 学習やコミュニケーションを通じて得た「文化」（ソフトウェア）が「人間」を作る
- 社会＝行動のもとになる知識、情報の流通の場所
- 社会学の焦点は「文化」と上記の「社会」　

# 感想
前回、生物進化のモデルに出てきた「乗り物」という言葉がうまく理解できなかったが、今回のハードウェアとソフトウェアの分離の話でしっかりとらえることができた。段々と社会学の実態に迫っている気がした。

# 代表者に対するフィードバック
「形式主義」の説明が、二つのものを並べて述べていてとても分かりやすかった。

**Comment by Rinne614** [comment]
# 小林凜音　グループ２
# 要約
 
**「形式」について**

・物質名詞＝形がない ex). water, cake 　局所性がない
・個体＝形がある ex.)生物としての個体　局所性がある
・形があるものは形がないものを素材にして出来上がる。

**生き物と社会における「形式」**

・生き物にとって素材＝タンパク質や水、形式＝遺伝情報
・社会にとって素材＝人間、形式＝知識や情報
・社会的存在としての人間の性質は「形式(＝知識と情報)」である。(それは学習とコミュニケーションによって刻みこまれる)
・社会的形式＝「文化」と言える。(文化は知識ふるまい方、言語、技術、生活習慣すべてをひっくるめている。)

**「文化」のダイナミズム‐コンピューターモデルの観点から‐**

・伝統的な機械＝形と働きが一体化している。
・コンピューター（万能機械）＝ハードウェアとソフトウェアが分離している。
・ハードウェアはソフトウェア次第で何でもできる。（＝ダイナミックである）
・コンピューターの出現は人間と社会の理解を促進させるモデル、「人間機械論」を提供した。

**「文化」‐人間機械論の観点から‐**

・人間を一種の「万能機械（＝学習で得た知識をもとにいろいろなことができる）」として理解する。
・人間におけるソフトウェア＝「文化」（学習とコミュニケーションを通じて獲得される）
・社会学者の関心は、ソフトウェアとしての「文化」と、その流通の仕組みとしての社会にある。

**「人間＝万能機械」というモデル**

・コンピューターの出現によって、「ソフトウェアが主、ハードウェアが従」というイメージが想像しやすくなった。
・また、「形式」がダイナミックであること(＝知識や情報が何かによって使われて初めて意味を持つこと)が思いだされた。
・「社会」＝情報の流通の場、人々が知識や情報を共有して相互作用する場　として理解されるようになる。

# 感想
科学的発明などから、社会と人の関係を理解しやすいモデルを考案し理解を深めることで、今回の章では人間機械論などの比較的わかりやすい概念などが紹介されたので、少しづつ社会学の根底にあるものに近づけているのではないかと感じた。
## 代表者のまとめに対するフィードバック
端的に説明されているので読みやすく、理解しやすかったです。私も人間を万能機械と捉える点が興味深いなと感じました。

**Comment by mi513** [comment]
# 大島美怜　グループ２
# 要約
#### 形式とは
・個体とは外の世界と切り離される境界線や境界面を持っていて、その境界があることによって「形」を保っている
・「形」＝「形式」

#### 社会学の「形式」
・社会学の場合人間という「素材」に対して社会的に共有される「知識」「情報」という「形式」が秩序を与える

#### 文化のダイナムズムをモデルとして考える
・コンピューターは「形式」を操作するに際して万能性を指している
・コンピューターが「計算」が出来る＝「形式」

#### コンピューターと様々なものの対比
・コンピューターのおけるソフトウェアとハードウェアは分離している
・普段使っているような電化製品などはそこに組み込まれているソフトを製品の一体化された部品としてのみ扱っていて切り離し可能なものだと思っていない
→コンピューターはそうではない
・コンピューターは形と働きに大きなずれがある

#### 万能機械
・人間もコンピューターと同じように特定の機能に特化して専用機械ではなく学習して得た知識を使用して様々なことが出来る万能機械である

#### ソフトウェアとしての文化
・コンピューターが発明されるまでソフトウェアとハードウェアの区別はなかった

# 感想
難しい内容だったけど比較的分かりやすい例や図を出して説明していたので理解できたと思う。また、前回説明されていた「形式」の意味がよくわからなかったけど理解することが出来た。

##  代表者のまとめに対するフィードバック
私が要約しきれていない部分まで丁寧に要約してあってより理解を深めることが出来ました。

**Comment by Johnsonliusw** [comment]
# グループ１　劉松蔚
# 要約
１、形式と内容
「内容」は生き物の構成単位である＜細胞＞。細胞を通じて、どんな「形式」を形成するのかが確定できる。

２、知識情報と人間の関係
例：生き物を構成する素材・材料である。うした素材に形が与え、生き物になる。また、生き物の性質を決めるのは、遺伝子という物質にある情報である。
＊社会学の立場にみると、人は生物的なヒトから離脱し、素材として知識情報を通じて社会的な存在になり、共有された知識情報は社会が構成できたおかげで、「文化」となる。
つまり、「形式」の主体がヒトから社会に変わるということだ。

３、万能機械
コンピュータ：形式操作：ハードウェアとソフトウェアを分離できる。
　　　　　　　計算：ハードウェアとしてソフトウェアを運用できる。
人間：　人間は乗り物（ハードウェア）として、全て使える道具はソフトウェアとして

４、ソフトウェアとしての文化
コンピュータ・ロボットの出現につれて、人間と機械の主従関係が変わった。
# 感想
ソフトウェアとしての文化に関する部分はわかりにくいでした。

**Comment by aisaaaaa** [comment]
# 橋本愛沙　グループ１
# 要約
**形式とは**
「個体 individual」…外の世界と切り離される境界線や境界面を持つ＝局地性
形あるもの（個体）は形ないもの（物質名詞）を素材として、「形」が与えられて出来上がる
この「形」を「形式」と呼ぶ

**社会学において人間に形式主義を当てはめる**
素材：人間　＋　形式：社会的に共有される知識、情報　＝　社会的な存在としての「人間」
（後天的に学習とコミュニケーションで刻み込まれる形式も存在）
「文化」＝社会学の固有の対象？
　　　　　学習とコミュニケーションを通じて獲得される知識やスキルと一致

**文化のダイナミズム**　Ex)コンピューター・モデル
コンピューターの大きな特徴として
１."万能機械"…「形式」を操作するに際しての万能性
２.ハードウェアとソフトウェアの分離…ソフトウェア次第で何でも計算できる

**ハードウェアとソフトウェアの分離**
伝統的・古典的機械はハードウェアとソフトウェアの分離がない　→形と働きの一体性
コンピューター　→その物理的実体と働きの間に大きなずれ

**コンピューター（万能機械）と人間のアナロジー**
人間におけるハードウェア：自由度の高い身体、汎用性の高い脳
　　　　　　ソフトウェア：遺伝、学習とコミュニケーションを通じて獲得される「文化」
社会学の関心はソフトウェアたる文化、その流通の仕組みとしての社会にある

**ソフトウェアとしての文化**
コンピューター及びそれが埋め込まれたロボットの出現によりソフトウェアが「主」、ハードウェアが「従」というイメージが想像しやすくなった
↓
知識・情報は行為の指針として使われて初めて意味を持つ
社会とはそれらを共有して相互作用する場
# 感想
今回は今まで抽象的に解説されていた箇所が具体や図を用いて説明されていたことから以前より理解できた。社会学が"どんなもので何をどのように目指しているのか"も文章内で徐々に固定化されてきたため、それをふまえて読み進めることができるようになってきた。

## その週の代表者のまとめに対するフィードバック
抽象的な内容の要約の前後に本文に載っている具体を付け加えており、理解の助けになった。

**Comment by yui423i** [comment]
# 石橋由衣　グループ2
# 要約

**形式とは**
物質名詞で名指されるようなものには「形」がなく、生き物のような個体には「形」がある。形あるものは形ないものを素材としてそこに「形」が与えられることによって出来上がる。
形を与えられる素材に対して「内容」「実質」といった言葉を当て、「形」の方を形式と呼ぶ。

**「形式」を人間で考える**
生き物の場合、水やタンパク質は素材でありそのような素材に形が与えられなければ生き物にならないので形を与える、形作るのに重要なのは遺伝子という物質にある情報、知識が形式にあたる。
社会学の場合、素材が人間であり、形式が知識・情報である。
生物学的なヒトの性質は進化論的に考えれば先天的に遺伝子に刻み込まれた一連の情報である形式、社会学的な人々が共有している知識や振る舞い方、言語や技術、生活習慣などの形式をひっくるめて広い意味での文化と呼ぶことができる。これらは学習とコミュニケーションを通して獲得される知識やスキルとほぼ一致している。

**文化のダイナミズム**
狭い意味でのコンピュータは昔と比べて情報処理、形式を操作する際に万能機械であるという特徴がある。つまり有限回の手順で実行できる作業だったらどんな作業でもできるということである。
又、ハードウェアとソフトウェアが分離しているという特徴もある。

**ハードウェアとソフトウェアの分離**
昔の機械や道具、パソコンは分離がなく構造と機能、形と働きの一体性・不可分性がある。しかしコンピュータがする仕事は他の機械である炊飯器や自動車に比べると非常に漠として一般的であり、より具体的な仕事のためには特定の仕事に合わせたアプリケーション・ソフトを使う。その形と働きの間に大きなズレがある。
人間で考えても人間もまた一種の万能機能である。特定の機能に特化した専用機械ではなく学習して得た知識を元に様々なことができる万能機械である。

**ソフトウェアとしての文化**
コンピュータの出現によりハードウェアとしての人間が主、ソフトウェアが従からはーdpウェアの方が従、ソフトウェアが主とイメージが想像しやすくなった。
このことにより知識・情報といった形式がダイナミックであること、知識・情報は行為の指針として使われて初めて意味を持つことを思い出しやすくした。
そして社会はそのような情報の流通の場、そこを通じて人々が知識、情報を共有して相互作用する場として理解されることになる。

# 感想
文章中に図が掲載されていたので今までより考えやすく、読みやすいと感じた。具体例など身近なもので理解しやすいと感じた。

理解し切れていないところもわかりやすくまとめてあったので理解が深まった。

**Comment by 21022163** [comment]
# 権田晴香　グループ１
# 要約
**1.形式とは**
・前提：物質名詞→数えられないもの、個体individual→数えられるもの
・この二つの違いは、「自分と外の世界とを区切る『境界』があるか否か」（個体はこれがある事によって形を保つ）
・形あるものは形のないものを素材としてできあがる。

**2.社会学における形式**
・人間という「素材」が社会的に共有された「意味」のネットワーク、知識のシステムに慣れることにより、社会学的な意味での人間になる。（学習とコミュニケーションによって刻み込まれる「形式」）
・社会学的に人々が共有しているもの全てひっくるめて「文化」と呼ぶ
　　　　　　　　→社会学の固有の対象は「文化」とも言える。しかし、これは人類学と一致する。

**3.文化のダイナミズム–コンピューター・モデルより**
・コンピューターは万能機械。（「形式」を操作するに際しての万能性を指す）
・ハードウェアとソフトウェアの分離→機能として意識する部分は、主としてソフトウェアにある。
　　　　　→形と働きの間にかなりずれがある。
＝第2講のロボット・モデルのモデル

**4.人間という名の万能機械**
・人間機械論のような考え方では、人間も一種の万能機械として理解されている。
　（学習して得た知識をもとに色々なことができる万能機会として）
・社会学の焦点は万能機会たる人間の方ではなく、インストールされるソフトウェアたる文化と、その流通の仕組みとしての社会

**5.ソフトウェアとしての文化**
・コンピューターは、ソフトウェアとハードウェアの働きなどと、物質的な物体との間にある程度ずれがある。
・「ハードウェアとしての人間が主、媒体に記録されたソフトウェアが従」だったのが、コンピューターの出現により、「ソフトウェアが主、ハードウェアが従」の想像を容易にした。
・そして社会とは、情報の流通の場、人々が知識・情報を共有して相互作用する場として理解されるようになった。
# 感想
説明に図がつくことで、より理解しやすくなった。人間を機械として捉え、社会を情報共有の場として捉えるということが、自分にとってはとても新しかった。
## 代表者のまとめに対するフィードバック
一つ一つことbを丁寧に噛み砕いて説明しており、内容をきちんと把握していない人にも伝わりやすいと思った。

**Comment by wakabamomii** [comment]
# 籾井若葉　グループ１
# 要約
**形式とは何か**
一個一個切り離されていて、別々に数えられるもの→「個体individual」
個体というのは外の世界と切り離される境界線や境界面を持っており、それによって「形」を保っている
形あるものは形ないものを素材として「形」が与えられることにより出来上がる
この「形」というものを「形式」と呼ぶ

**形式を人間に当てはめる**
生き物の素材はタンパク質や水、形式は遺伝情報
それに対し社会学の場合は素材が「人間」、形式は社会的に共有される「知識」「情報」
知識や振る舞い方、言語や技術、生活習慣などの社会的な形式→「文化」(社会学の固有の対象)
→学習とコミュニケーションを通じて獲得される知識やスキルとほぼ一致

**「文化」のダイナミズムについて考える**
コンピューター→「情報処理」「形式」を操作するのに万能な機械
　　　　　　　　ハードウェアとソフトウェアが分離している
→有限回の手順で実行できる作業なら何でも出来る

**ハードウェアとソフトウェアの分離**
古典的な機械にはハードウェアとソフトウェアの分離がなく、構造と機能、形と働きの一体性・不可分性が表れている
コンピューターは形と働きの間に大きなズレがある→道具として使う時、ソフトウェアに拠っている

**人間は万能機能？**
人間機械論では人間も一種の万能機械として理解されている(学習して得た知識を用いていろんなことが出来る)

**ソフトウェアとしての文化**
コンピューター→動き、用途、機能と物理的な実体との間に少しのズレがある
「形式」が本来ダイナミックなものであること、「知識」「情報」は行為の指針として使われて初めて意味を持つ
→社会とは、情報の流通の場を通じて人々が知識や情報を共有して相互作用する場

## 感想
イラストを用いた説明もあり、前回より理解が深まったように思う。コンピューターについての話題は身近に感じることができ、分かりやすかった。

## その週の代表者のまとめに対するフィードバック
箇条書きでとても分かりやすく要約されていたので理解しやすく、自分が要約するにあたって参考になる部分が多くあった。

**Comment by KarenTakamatsu** [comment]
# 髙松かれん　グループ１
# 要約

**1. 形式と内容**
・「形式」は「内容」「実質」「中身」に対比する。
・「物質名詞（水,粉,ケーキなど）」は個体が集まった全体のまとまり　⇔　「個体:individual」は一個一個切り離されているもの
　　＝形ナシ　　　　　　　　　　　　　　　　　　　　　　　　　　　　　＝形アリ
・上記の違いは、外の世界と切り離される境界線や境界面を持っていること。
・形が与えられる素材を「内容」「実質」と呼ぶ。形を「形式」と呼ぶ。

**2.社会学と知識と情報による人間の形成**
・素材や材料に形が与えられるからこそ「生き物」が存在する。
・社会学の場合、素材に対して社会に共有される「知識」「情報」という形式が秩序を与える。
・人間の性質は学習やコミュニケーションによって形成される形式である。
・「文化」は学習とコミュニケーションを通して知識やスキルを獲得。
・人類学と社会学は似ている。
　人類学 → 伝統社会を扱う　 社会学 → 文明社会,近代社会を扱う

**3.コンピュータをモデルとして「文化」のダイナミズムを考える**
・コンピュータは情報処理や形式を操作する万能機能。
・人間は特定の機能に特化した専用機械ではなく、学習として得た知識をもとに様々なことができる万能機械である。
・コンピュータには「ハードウェア」と「ソフトウェア」が分離している。
　　　　　　　　  　＝物理的機械　      ＝プログラミング
・ソフトウェア次第でハードウェアが基本的に何でも出来る。

**4.ハードウェアとソフトウェアの分離**
・伝統的な機会は分離がない。
・私たちは組み込まれているソフトを構造と機会、形と働きの一体性がはっきりしているものとして扱っている。
　切り離し可能なものとしては扱っていない。
・コンピュータにおいては形と働きに大きなズレはある。
・コンピュータのモデルと、「意味」の社会理論との間にアナロジーが成立。

**5.ソフトウェアの文化**
・コンピュータの本格的な出現までハードウェアとソフトウェアの区別という発想自体なかった。
・コンピュータによって「知識」「情報」さらに「形式」がダイナミックであること、また社会とは情報の流通の場として理解される。

## 感想
今回の章には絵や図が用いられており、いつもより具体例が多かったのて、内容理解がしやすかったと感じました。また章を読み進めるごとに社会学について段々わかることが増えてきていると思いました。

## 代表者のまとめに対するフィードバック
とてもわかりやすい要約だったため、たくさん参考にさせていただきました。

**Comment by AyariNomura** [comment]
# 野村彩莉　グループ１
# 要約
　外の世界と切り離される境界線や境界面を持っており、一個一個切り離されて別々に数えられるものを「個体individual」という。形あるものは形ないものを素材として「形」が与えられることにより出来上がり、その形を「形式」と呼ぶ。社会学においては「人間」を素材とし、社会的に共有される「知識」「情報」を形式とする。知識や振る舞い方、言語や技術、生活習慣といった社会的な形式を「文化」と呼ぶことができ、学習とコミュニケーションを通じて獲得される知識やスキルとほぼ一致する。コンピューターをモデルにして考えてみると、コンピューターは万能機械でありハードウェアとソフトウェアが分離しているため、有限回の手順で実行できる作業の場合、どんな作業も可能である。それに対し、伝統的な機械はハードウェアとソフトウェアが分離しておらず、組み込まれているソフトを製品の一体化された部品として飲み扱い、切り離し可能なものとしては扱っていない。コンピュータの出現によりハードウェアとしての人間が主、ソフトウェアが従からはーdpウェアの方が従、ソフトウェアが主とイメージが想像しやすくなったことでったことで、知識・情報といった形式が行為の指針として使われて初めて意味を持つことを思い出しやすくなった。そして、社会はそのような情報の流通の場、そこを通じて人々が知識情報を共有し相互作用する場として理解されることになる。

# 感想
　図が用いられていたことで分かりやすく、前回までの内容と繋がっていた部分があってより理解を深めることができた。

**Comment by HirotoGoto** [comment]
# 後藤洸登　グループ１
# 要約
**形式とは**
・「形式」は「内容」「実質」「中身」に対比する。
・物質名詞 → 数えられないもの。外の世界と切り離されるための境界線を持たない。  
　　ex.）水、粉、ケーキ
・個体 → 数えられ、個体を形成するもの。境界線を保有する。
・形あるもの（個体）は形ないもの（物質名詞）を素材として、「形」が与えられて出来上がる。
　→　この「形」を「形式」と呼ぶ。

**人と社会学における「形式」**
・人 → タンパク質や水といった「素材」に、遺伝情報という「形式」を与えることで、存在する。
・社会 → 人間が「素材」、知識や情報が「形式」となる。

**「文化」のダイナミズム**
・コンピューター → 「情報処理」「形式」を操作する点では、万能機械  
　ハードウェアとソフトウェアが分離している
　　→有限回の手順で実行できる作業ならどんな作業も可能である。

**ハードウェアとソフトウェアの分離**
・古典的な機械にはハードウェアとソフトウェアの分離がない。
・コンピューターは分離している。

**人間と万能機械**
・人間は特定の機能に特化しておらず、学習して得た知識を用いて様々なことを行える。
・この点から、人間も万能機械の一種であるといえる。

**ソフトウェアとしての文化**
・コンピューターの出現により、「ソフトウェアが主、ハードウェアが従」という関係性が容易に想像できるように変化した。
・「社会」 ＝ 情報の流通の場、人々が知識や情報を共有して相互作用する場　と理解できる。　

## 感想
　例やイラストが増えたことで、理解しながら読むことができた。形式についての説明が足されていたため、前回より理解を深められたと思う。

## その週の代表者のまとめに対するフィードバック
　それぞれの項を箇条書きで、かつ詳しく書いていたため、わかりやすかった。

**Comment by shofukurono** [comment]
# 袋野奨　グループ２

# 要約
* 形式と内容
物質名詞で名指されるようなものには、「形」がなく、局所性をもつ個体であるものには「形」がない。
形が与えられる素材を「内容」「実質」と呼ぶ。形を「形式」と呼ぶ。

* ハードウェアとソフトウェアの分離
古典的な機械では、一つの機械はひとつの役割しか果たせなかった。ex,炊飯器
だが、パソコンは計算、お絵かき、ゲーム様々なことができる。それはハードウェアとソフトウェアの分離しているからだ。

* 人間という万能機械
人間も特定の機能に特化した専用機械ではなく、学習して得た知識を用いて様々なことを行える万能機械である。
人間のソフトウェアのひとつに「文化」があげられる。社会学関心の焦点は、ソフトウェアである文化と流通のしくみである社会のほうである。

*ソフトウェアとしての文化
コンピューターの出現によってハードウェアが主ソフトウェアが従という関係がソフトウェアが主、ハードウェアが従という関係が想像しやすくなった。
 

# 感想
読んでいて筆者の伝えたいことがどのような具体例を介して説明されているのかを読み取るのが難しいなと感じた。

# その週の代表者のまとめに対するフィードバック
各項のキーワードが強調されていたり筆者の考えの部分が抜き出されていてわかりやすかった。

**Comment by seshitamayu** [comment]
# 瀬下茉由　グループ2
# 要約
### 形式と内容
・「空間的に限られた場所に位置している」という性質が入っているという意味の「局地性」という性質が「個体」には入っている。
・形のあるものは、形のないものを素材として「形」を保っている。
### 社会学における形式
・生き物；水・たんぱく質＝素材 , 遺伝子＝形式 , 個体＝現実の具体的な存在者
・社会学；ヒト＝素材 , 知識・情報 , 人間＝社会的な存在としての人間
### 文化のダイナミズム
・「情報処理」としての「形式」を操作するに際しての万能性がコンピューターにはある。
・ハードウェアとソフトウェアが分離していて、ソフトウェア次第で基本的に何でもできる。
→有限回の手順で実行できる作業だったらどんな作業でもできる。
### ハードウェアとソフトウェアの分離
・コンピューターにはハードウェアとソフトウェアの分離があるが、古典的な機械にはない。
・古典的な機械は特定の仕事をするために構造と機能、形と働きの一定性・不可分性がある。
### 人間という万能機械
・人間を、特定の機能に特化した専用機械ではなく、学習して得た知識をもとに色々なことができる万能機械として理解することができる。
・学習とコミュニケーションを通じて獲得されるソフトウェアとして「文化」がある。
### ソフトウェアとしての文化
・コンピューターは働き、用途、機能と、物理的な実体との間に、ある程度のずれが生じている。
・コンピューター、ロボットの出現によって、ソフトウェアの方が主、ハードウェアの方が従、というイメージが容易に想像できるようになっている。

# 感想
文章の間のイラストによって可視化されていて、理解しやすかった。
コンピューターと人間が比較され、同じように説明されるものだとは思わなかったため、驚きだった。
# その週の代表者のまとめに対するフィードバック
自分がまとめきれなかった部分も、それぞれの段落において重要な箇所や例なども取り上げて丁寧に要約していて、とても分かりやすかった。

**Comment by SayakaFujikawa** [comment]
# 藤川紗亜花　グループ１
# 要約
**社会学における形式と内容**
ここでは「内容」は形のないものを、「形式」を形そのものとして捉える。
たとえば生き物にとっての内容はタンパク質や水で、形式は遺伝子である。
そして社会学においての内容は生物学的な「ヒト」で、形式は知識や情報である。これによりヒトは初めて社会学的な「個人」になる。
社会学においての形式が「知識や情報」であれば、それはひとえに「文化」だといえる。形式主義で社会学の固有の対象を決めるのならば、社会学の対象は「文化」であるといえる。
**文化のダイナミズム**
文化をコンピューターのソフトウェアとのアナロジーで考える。
コンピューターは従来のものと異なり、ハードウェアとソフトウェアが分離しているため、ソフトウェアによっていろいろな「形式」の操作が可能になり、万能となった。
文化もソフトウェアと同じように、いろいろな「形式」の操作を可能にし、、社会にダイナミズムをもたらす。
人間も学習した「形式」を操作する点でコンピューターのような万能機械だと理解されている。
ソフトウェアとしての文化
コンピューターの登場により、ソフトウェアが主、ハードウェアが従であることが想像しやすくなり、「形式」とは本来吸収したのちに使われて初めて意味を持つということも思い出しやすくなった。
社会とは「形式」が流通し、共有される場であると理解される。

# 感想
文化のダイナミズムあたりから少し話が複雑になって読むほどく必要があったように思う。でもやはり文が理解されやすいように書いてあって、わからずに調べた単語も少なめに思えた。コンピューターの例は考えたこともないようなことだったため、すごく楽しみながら読むことができた。

# その週の代表者のまとめに対するフィードバック
箇条書きでの要約でもわかりやすくまとまっていて、とても参考になった。

**Comment by yadoiwa** [comment]
# 宿岩芽梨香　グループ2
# 要約
#### 形式
実質や中身に対して形式という言葉がある。これは局所性という性質を持つ個体である。個体の典型例として生き物があげられる。自分と外の世界を区切る境界があることで生物個体は身体の形を保つ。この形を形式と呼ぶ。
#### 知識、情報
社会学では人間という素材に対して社会的に共有される知識、情報という形式が秩序を与えると考える。社会学的な存在としての人間の性質は学習とコミュニケーションによって刻み込まれる形式である。
#### ソフトウェアとハードウェア
現代的なコンピューターはハードウェアとソフトウェが分離している。そして情報処理、つまり形式を操作する際に万能であり、コンピューター自体は様々なソフトウェアを動かすことが出来てソフトウェア次第で多様な仕事をしてくれる。一方、伝統的な機会はハードウェアとソフトウェアの分離がなく、本来の機能、特定の仕事を果たすための形をしている。構造と機能、形と働きの一体性、不可分性がはっきりと表れる
#### ソフトウェアと文化
人間は学習して得た知識をもとに様々なことが出来る万能機械として理解されている。さらに学習とコミュニケーションを通じて獲得されるソフトウェアとしての文化が人間を人間たらしめている。そして社会は、情報の流通場、そこを通じて人々が知識、情報を共有して相互作用する場として理解される。
#### 社会の成立
社会学の自立点は19世紀末から20世紀初頭である。またさらにその前提にさかのぼるなら17世紀になる。
